// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	types "github.com/smartcontractkit/chainlink-common/pkg/types"
	chain "github.com/smartcontractkit/chainlink-stellar/relayer/chain"
	config "github.com/smartcontractkit/chainlink-stellar/relayer/config"
	mock "github.com/stretchr/testify/mock"
)

// MockChain is an autogenerated mock type for the Chain type
type MockChain struct {
	mock.Mock
}

type MockChain_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChain) EXPECT() *MockChain_Expecter {
	return &MockChain_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockChain) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChain_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockChain_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockChain_Expecter) Close() *MockChain_Close_Call {
	return &MockChain_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockChain_Close_Call) Run(run func()) *MockChain_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_Close_Call) Return(_a0 error) *MockChain_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Close_Call) RunAndReturn(run func() error) *MockChain_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *MockChain) Config() *config.TOMLConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *config.TOMLConfig
	if rf, ok := ret.Get(0).(func() *config.TOMLConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.TOMLConfig)
		}
	}

	return r0
}

// MockChain_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockChain_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockChain_Expecter) Config() *MockChain_Config_Call {
	return &MockChain_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockChain_Config_Call) Run(run func()) *MockChain_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_Config_Call) Return(_a0 *config.TOMLConfig) *MockChain_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Config_Call) RunAndReturn(run func() *config.TOMLConfig) *MockChain_Config_Call {
	_c.Call.Return(run)
	return _c
}

// FinalizedHead provides a mock function with given fields: ctx
func (_m *MockChain) FinalizedHead(ctx context.Context) (types.Head, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FinalizedHead")
	}

	var r0 types.Head
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.Head, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.Head); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(types.Head)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChain_FinalizedHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizedHead'
type MockChain_FinalizedHead_Call struct {
	*mock.Call
}

// FinalizedHead is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChain_Expecter) FinalizedHead(ctx interface{}) *MockChain_FinalizedHead_Call {
	return &MockChain_FinalizedHead_Call{Call: _e.mock.On("FinalizedHead", ctx)}
}

func (_c *MockChain_FinalizedHead_Call) Run(run func(ctx context.Context)) *MockChain_FinalizedHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChain_FinalizedHead_Call) Return(_a0 types.Head, _a1 error) *MockChain_FinalizedHead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChain_FinalizedHead_Call) RunAndReturn(run func(context.Context) (types.Head, error)) *MockChain_FinalizedHead_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainInfo provides a mock function with given fields: ctx
func (_m *MockChain) GetChainInfo(ctx context.Context) (types.ChainInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChainInfo")
	}

	var r0 types.ChainInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.ChainInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.ChainInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(types.ChainInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChain_GetChainInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainInfo'
type MockChain_GetChainInfo_Call struct {
	*mock.Call
}

// GetChainInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChain_Expecter) GetChainInfo(ctx interface{}) *MockChain_GetChainInfo_Call {
	return &MockChain_GetChainInfo_Call{Call: _e.mock.On("GetChainInfo", ctx)}
}

func (_c *MockChain_GetChainInfo_Call) Run(run func(ctx context.Context)) *MockChain_GetChainInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChain_GetChainInfo_Call) Return(_a0 types.ChainInfo, _a1 error) *MockChain_GetChainInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChain_GetChainInfo_Call) RunAndReturn(run func(context.Context) (types.ChainInfo, error)) *MockChain_GetChainInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainStatus provides a mock function with given fields: ctx
func (_m *MockChain) GetChainStatus(ctx context.Context) (types.ChainStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChainStatus")
	}

	var r0 types.ChainStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.ChainStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.ChainStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(types.ChainStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChain_GetChainStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainStatus'
type MockChain_GetChainStatus_Call struct {
	*mock.Call
}

// GetChainStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChain_Expecter) GetChainStatus(ctx interface{}) *MockChain_GetChainStatus_Call {
	return &MockChain_GetChainStatus_Call{Call: _e.mock.On("GetChainStatus", ctx)}
}

func (_c *MockChain_GetChainStatus_Call) Run(run func(ctx context.Context)) *MockChain_GetChainStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChain_GetChainStatus_Call) Return(_a0 types.ChainStatus, _a1 error) *MockChain_GetChainStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChain_GetChainStatus_Call) RunAndReturn(run func(context.Context) (types.ChainStatus, error)) *MockChain_GetChainStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with no fields
func (_m *MockChain) GetClient() (chain.RPCClient, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 chain.RPCClient
	var r1 error
	if rf, ok := ret.Get(0).(func() (chain.RPCClient, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() chain.RPCClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chain.RPCClient)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChain_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockChain_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *MockChain_Expecter) GetClient() *MockChain_GetClient_Call {
	return &MockChain_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *MockChain_GetClient_Call) Run(run func()) *MockChain_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_GetClient_Call) Return(_a0 chain.RPCClient, _a1 error) *MockChain_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChain_GetClient_Call) RunAndReturn(run func() (chain.RPCClient, error)) *MockChain_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// HealthReport provides a mock function with no fields
func (_m *MockChain) HealthReport() map[string]error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthReport")
	}

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func() map[string]error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// MockChain_HealthReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthReport'
type MockChain_HealthReport_Call struct {
	*mock.Call
}

// HealthReport is a helper method to define mock.On call
func (_e *MockChain_Expecter) HealthReport() *MockChain_HealthReport_Call {
	return &MockChain_HealthReport_Call{Call: _e.mock.On("HealthReport")}
}

func (_c *MockChain_HealthReport_Call) Run(run func()) *MockChain_HealthReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_HealthReport_Call) Return(_a0 map[string]error) *MockChain_HealthReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_HealthReport_Call) RunAndReturn(run func() map[string]error) *MockChain_HealthReport_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockChain) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChain_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockChain_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockChain_Expecter) ID() *MockChain_ID_Call {
	return &MockChain_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockChain_ID_Call) Run(run func()) *MockChain_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_ID_Call) Return(_a0 string) *MockChain_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_ID_Call) RunAndReturn(run func() string) *MockChain_ID_Call {
	_c.Call.Return(run)
	return _c
}

// LatestHead provides a mock function with given fields: ctx
func (_m *MockChain) LatestHead(ctx context.Context) (types.Head, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LatestHead")
	}

	var r0 types.Head
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.Head, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.Head); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(types.Head)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChain_LatestHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestHead'
type MockChain_LatestHead_Call struct {
	*mock.Call
}

// LatestHead is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChain_Expecter) LatestHead(ctx interface{}) *MockChain_LatestHead_Call {
	return &MockChain_LatestHead_Call{Call: _e.mock.On("LatestHead", ctx)}
}

func (_c *MockChain_LatestHead_Call) Run(run func(ctx context.Context)) *MockChain_LatestHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChain_LatestHead_Call) Return(_a0 types.Head, _a1 error) *MockChain_LatestHead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChain_LatestHead_Call) RunAndReturn(run func(context.Context) (types.Head, error)) *MockChain_LatestHead_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodeStatuses provides a mock function with given fields: ctx, pageSize, pageToken
func (_m *MockChain) ListNodeStatuses(ctx context.Context, pageSize int32, pageToken string) ([]types.NodeStatus, string, int, error) {
	ret := _m.Called(ctx, pageSize, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for ListNodeStatuses")
	}

	var r0 []types.NodeStatus
	var r1 string
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) ([]types.NodeStatus, string, int, error)); ok {
		return rf(ctx, pageSize, pageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string) []types.NodeStatus); ok {
		r0 = rf(ctx, pageSize, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.NodeStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string) string); ok {
		r1 = rf(ctx, pageSize, pageToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int32, string) int); ok {
		r2 = rf(ctx, pageSize, pageToken)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int32, string) error); ok {
		r3 = rf(ctx, pageSize, pageToken)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockChain_ListNodeStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodeStatuses'
type MockChain_ListNodeStatuses_Call struct {
	*mock.Call
}

// ListNodeStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - pageSize int32
//   - pageToken string
func (_e *MockChain_Expecter) ListNodeStatuses(ctx interface{}, pageSize interface{}, pageToken interface{}) *MockChain_ListNodeStatuses_Call {
	return &MockChain_ListNodeStatuses_Call{Call: _e.mock.On("ListNodeStatuses", ctx, pageSize, pageToken)}
}

func (_c *MockChain_ListNodeStatuses_Call) Run(run func(ctx context.Context, pageSize int32, pageToken string)) *MockChain_ListNodeStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockChain_ListNodeStatuses_Call) Return(stats []types.NodeStatus, nextPageToken string, total int, err error) *MockChain_ListNodeStatuses_Call {
	_c.Call.Return(stats, nextPageToken, total, err)
	return _c
}

func (_c *MockChain_ListNodeStatuses_Call) RunAndReturn(run func(context.Context, int32, string) ([]types.NodeStatus, string, int, error)) *MockChain_ListNodeStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockChain) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChain_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockChain_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockChain_Expecter) Name() *MockChain_Name_Call {
	return &MockChain_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockChain_Name_Call) Run(run func()) *MockChain_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_Name_Call) Return(_a0 string) *MockChain_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Name_Call) RunAndReturn(run func() string) *MockChain_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockChain) Ready() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChain_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockChain_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockChain_Expecter) Ready() *MockChain_Ready_Call {
	return &MockChain_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockChain_Ready_Call) Run(run func()) *MockChain_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChain_Ready_Call) Return(_a0 error) *MockChain_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Ready_Call) RunAndReturn(run func() error) *MockChain_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Replay provides a mock function with given fields: ctx, fromBlock, args
func (_m *MockChain) Replay(ctx context.Context, fromBlock string, args map[string]any) error {
	ret := _m.Called(ctx, fromBlock, args)

	if len(ret) == 0 {
		panic("no return value specified for Replay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]any) error); ok {
		r0 = rf(ctx, fromBlock, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChain_Replay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replay'
type MockChain_Replay_Call struct {
	*mock.Call
}

// Replay is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock string
//   - args map[string]any
func (_e *MockChain_Expecter) Replay(ctx interface{}, fromBlock interface{}, args interface{}) *MockChain_Replay_Call {
	return &MockChain_Replay_Call{Call: _e.mock.On("Replay", ctx, fromBlock, args)}
}

func (_c *MockChain_Replay_Call) Run(run func(ctx context.Context, fromBlock string, args map[string]any)) *MockChain_Replay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]any))
	})
	return _c
}

func (_c *MockChain_Replay_Call) Return(_a0 error) *MockChain_Replay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Replay_Call) RunAndReturn(run func(context.Context, string, map[string]any) error) *MockChain_Replay_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockChain) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChain_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockChain_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockChain_Expecter) Start(_a0 interface{}) *MockChain_Start_Call {
	return &MockChain_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockChain_Start_Call) Run(run func(_a0 context.Context)) *MockChain_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChain_Start_Call) Return(_a0 error) *MockChain_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Start_Call) RunAndReturn(run func(context.Context) error) *MockChain_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Transact provides a mock function with given fields: ctx, from, to, amount, balanceCheck
func (_m *MockChain) Transact(ctx context.Context, from string, to string, amount *big.Int, balanceCheck bool) error {
	ret := _m.Called(ctx, from, to, amount, balanceCheck)

	if len(ret) == 0 {
		panic("no return value specified for Transact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *big.Int, bool) error); ok {
		r0 = rf(ctx, from, to, amount, balanceCheck)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChain_Transact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transact'
type MockChain_Transact_Call struct {
	*mock.Call
}

// Transact is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - to string
//   - amount *big.Int
//   - balanceCheck bool
func (_e *MockChain_Expecter) Transact(ctx interface{}, from interface{}, to interface{}, amount interface{}, balanceCheck interface{}) *MockChain_Transact_Call {
	return &MockChain_Transact_Call{Call: _e.mock.On("Transact", ctx, from, to, amount, balanceCheck)}
}

func (_c *MockChain_Transact_Call) Run(run func(ctx context.Context, from string, to string, amount *big.Int, balanceCheck bool)) *MockChain_Transact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*big.Int), args[4].(bool))
	})
	return _c
}

func (_c *MockChain_Transact_Call) Return(_a0 error) *MockChain_Transact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChain_Transact_Call) RunAndReturn(run func(context.Context, string, string, *big.Int, bool) error) *MockChain_Transact_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChain creates a new instance of MockChain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChain(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChain {
	mock := &MockChain{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
