// Code generated by stellar-bindings-generator. DO NOT EDIT.
package router

import (
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// OnRampEntry represents the OnRampEntry struct from the contract.
type OnRampEntry struct {
	DestChainSelector uint64
	Onramp string
}

// ToScVal converts OnRampEntry to an xdr.ScVal for contract calls.
func (s OnRampEntry) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"onramp": scval.AddressToScVal(s.Onramp),
	})
}

// OnRampEntryFromScVal parses an xdr.ScVal into OnRampEntry.
func OnRampEntryFromScVal(val xdr.ScVal) (*OnRampEntry, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &OnRampEntry{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "onramp":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("onramp: %w", err)
			}
			result.Onramp = v
		}
	}

	return result, nil
}

// OffRampEntry represents the OffRampEntry struct from the contract.
type OffRampEntry struct {
	Offramp string
	SourceChainSelector uint64
}

// ToScVal converts OffRampEntry to an xdr.ScVal for contract calls.
func (s OffRampEntry) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"offramp": scval.AddressToScVal(s.Offramp),
		"source_chain_selector": scval.Uint64ToScVal(s.SourceChainSelector),
	})
}

// OffRampEntryFromScVal parses an xdr.ScVal into OffRampEntry.
func OffRampEntryFromScVal(val xdr.ScVal) (*OffRampEntry, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &OffRampEntry{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "offramp":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("offramp: %w", err)
			}
			result.Offramp = v
		case "source_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("source_chain_selector: %w", err)
			}
			result.SourceChainSelector = v
		}
	}

	return result, nil
}

// RouterConfig represents the RouterConfig struct from the contract.
type RouterConfig struct {
	RmnProxy string
}

// ToScVal converts RouterConfig to an xdr.ScVal for contract calls.
func (s RouterConfig) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"rmn_proxy": scval.AddressToScVal(s.RmnProxy),
	})
}

// RouterConfigFromScVal parses an xdr.ScVal into RouterConfig.
func RouterConfigFromScVal(val xdr.ScVal) (*RouterConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &RouterConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "rmn_proxy":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("rmn_proxy: %w", err)
			}
			result.RmnProxy = v
		}
	}

	return result, nil
}

// TokenAmount represents the TokenAmount struct from the contract.
type TokenAmount struct {
	Amount int64
	Token string
}

// ToScVal converts TokenAmount to an xdr.ScVal for contract calls.
func (s TokenAmount) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"amount": scval.I128ToScVal(s.Amount),
		"token": scval.AddressToScVal(s.Token),
	})
}

// TokenAmountFromScVal parses an xdr.ScVal into TokenAmount.
func TokenAmountFromScVal(val xdr.ScVal) (*TokenAmount, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenAmount{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("amount: %w", err)
			}
			result.Amount = v
		case "token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// AnyToStellarMessage represents the AnyToStellarMessage struct from the contract.
type AnyToStellarMessage struct {
	Placeholder uint64
}

// ToScVal converts AnyToStellarMessage to an xdr.ScVal for contract calls.
func (s AnyToStellarMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"placeholder": scval.Uint64ToScVal(s.Placeholder),
	})
}

// AnyToStellarMessageFromScVal parses an xdr.ScVal into AnyToStellarMessage.
func AnyToStellarMessageFromScVal(val xdr.ScVal) (*AnyToStellarMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AnyToStellarMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "placeholder":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("placeholder: %w", err)
			}
			result.Placeholder = v
		}
	}

	return result, nil
}

// StellarToAnyMessage represents the StellarToAnyMessage struct from the contract.
type StellarToAnyMessage struct {
	Data []byte
	ExtraArgs []byte
	FeeToken string
	Receiver []byte
	TokenAmounts []TokenAmount
}

// ToScVal converts StellarToAnyMessage to an xdr.ScVal for contract calls.
func (s StellarToAnyMessage) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"data": scval.BytesToScVal(s.Data),
		"extra_args": scval.BytesToScVal(s.ExtraArgs),
		"fee_token": scval.AddressToScVal(s.FeeToken),
		"receiver": scval.BytesToScVal(s.Receiver),
		"token_amounts": scval.StructSliceToScVal(s.TokenAmounts),
	})
}

// StellarToAnyMessageFromScVal parses an xdr.ScVal into StellarToAnyMessage.
func StellarToAnyMessageFromScVal(val xdr.ScVal) (*StellarToAnyMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StellarToAnyMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("data is not bytes")
			}
			result.Data = []byte(v)
		case "extra_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("extra_args is not bytes")
			}
			result.ExtraArgs = []byte(v)
		case "fee_token":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token: %w", err)
			}
			result.FeeToken = v
		case "receiver":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("receiver is not bytes")
			}
			result.Receiver = []byte(v)
		case "token_amounts":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("token_amounts is not a vec")
			}
			result.TokenAmounts = make([]TokenAmount, len(*vec))
			for i, item := range *vec {
				v, err := TokenAmountFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.TokenAmounts[i] = *v
			}
		}
	}

	return result, nil
}

// RouterError represents the contract error codes.
const (
	RouterErrorAlreadyInitialized = 1
	RouterErrorNotInitialized = 2
	RouterErrorUnauthorized = 3
	RouterErrorUnsupportedDestinationChain = 4
	RouterErrorInsufficientFeeTokenAmount = 5
	RouterErrorInvalidMsgValue = 6
	RouterErrorBadRMNSignal = 7
	RouterErrorOffRampMismatch = 8
	RouterErrorInvalidRecipientAddress = 9
	RouterErrorFailedToSendValue = 10
	RouterErrorOnRampError = 11
	RouterErrorOffRampAlreadyExists = 12
)

// RouterErrorMessage returns a human-readable message for error codes.
var RouterErrorMessage = map[int]string{
	1: "already initialized",
	2: "not initialized",
	3: "unauthorized",
	4: "unsupported destination chain",
	5: "insufficient fee token amount",
	6: "invalid msg value",
	7: "bad r m n signal",
	8: "off ramp mismatch",
	9: "invalid recipient address",
	10: "failed to send value",
	11: "on ramp error",
	12: "off ramp already exists",
}

// AuthError represents the contract error codes.
const (
	AuthErrorNotInitialized = 1
	AuthErrorUnauthorized = 2
	AuthErrorNotOwner = 3
	AuthErrorNoPendingOwner = 4
	AuthErrorCallerNotAuthorized = 5
	AuthErrorCallerAlreadyAuthorized = 6
	AuthErrorCallerNotFound = 7
	AuthErrorRoleNotGranted = 8
	AuthErrorFeatureNotEnabled = 9
	AuthErrorRoleAlreadyGranted = 10
	AuthErrorCannotRenounceRole = 11
)

// AuthErrorMessage returns a human-readable message for error codes.
var AuthErrorMessage = map[int]string{
	1: "not initialized",
	2: "unauthorized",
	3: "not owner",
	4: "no pending owner",
	5: "caller not authorized",
	6: "caller already authorized",
	7: "caller not found",
	8: "role not granted",
	9: "feature not enabled",
	10: "role already granted",
	11: "cannot renounce role",
}

// OnRampSetEvent represents the OnRampSetEvent event.
// Topics: [router_OnRampSet]
type OnRampSetEvent struct {
	DestChainSelector uint64
	Onramp string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OnRampSetEventTopic is the event topic identifier.
const OnRampSetEventTopic = "router_OnRampSet"

// OffRampAddedEvent represents the OffRampAddedEvent event.
// Topics: [router_OffRampAdded]
type OffRampAddedEvent struct {
	SourceChainSelector uint64
	Offramp string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OffRampAddedEventTopic is the event topic identifier.
const OffRampAddedEventTopic = "router_OffRampAdded"

// OffRampRemovedEvent represents the OffRampRemovedEvent event.
// Topics: [router_OffRampRemoved]
type OffRampRemovedEvent struct {
	SourceChainSelector uint64
	Offramp string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OffRampRemovedEventTopic is the event topic identifier.
const OffRampRemovedEventTopic = "router_OffRampRemoved"

// MessageExecutedEvent represents the MessageExecutedEvent event.
// Topics: [router_MessageExecuted]
type MessageExecutedEvent struct {
	MessageId [32]byte
	SourceChainSelector uint64
	Offramp string
	// Event metadata
	Ledger uint32
	TxHash string
}

// MessageExecutedEventTopic is the event topic identifier.
const MessageExecutedEventTopic = "router_MessageExecuted"

// CCIPSendRequestedEvent represents the CCIPSendRequestedEvent event.
// Topics: [router_CCIPSendRequested]
type CCIPSendRequestedEvent struct {
	MessageId [32]byte
	DestChainSelector uint64
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// CCIPSendRequestedEventTopic is the event topic identifier.
const CCIPSendRequestedEventTopic = "router_CCIPSendRequested"

// RoleGrantedEvent represents the RoleGrantedEvent event.
// Topics: [auth_RoleGranted]
type RoleGrantedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleGrantedEventTopic is the event topic identifier.
const RoleGrantedEventTopic = "auth_RoleGranted"

// RoleRevokedEvent represents the RoleRevokedEvent event.
// Topics: [auth_RoleRevoked]
type RoleRevokedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleRevokedEventTopic is the event topic identifier.
const RoleRevokedEventTopic = "auth_RoleRevoked"

// OwnershipTransferredEvent represents the OwnershipTransferredEvent event.
// Topics: [auth_OwnerTransferred]
type OwnershipTransferredEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferredEventTopic is the event topic identifier.
const OwnershipTransferredEventTopic = "auth_OwnerTransferred"

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

