// Code generated by stellar-bindings-generator. DO NOT EDIT.
package ramp_registry

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// RampRegistryClient provides methods to interact with the RampRegistry contract.
type RampRegistryClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewRampRegistryClient creates a new RampRegistryClient.
func NewRampRegistryClient(invoker bindings.Invoker, contractID string) *RampRegistryClient {
	return &RampRegistryClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *RampRegistryClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *RampRegistryClient) Owner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// IsOwner calls the is_owner function on the contract.
func (c *RampRegistryClient) IsOwner(ctx context.Context, addr string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(addr),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_owner", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_owner: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_owner")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// InitOwner calls the init_owner function on the contract.
func (c *RampRegistryClient) InitOwner(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "init_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call init_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// RequireOwner calls the require_owner function on the contract.
func (c *RampRegistryClient) RequireOwner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "require_owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call require_owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from require_owner")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *RampRegistryClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// AcceptOwnership calls the accept_ownership function on the contract.
func (c *RampRegistryClient) AcceptOwnership(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "accept_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call accept_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// GetPendingOwner calls the get_pending_owner function on the contract.
func (c *RampRegistryClient) GetPendingOwner(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pending_owner", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_pending_owner: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_pending_owner")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// CancelOwnershipTransfer calls the cancel_ownership_transfer function on the contract.
func (c *RampRegistryClient) CancelOwnershipTransfer(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "cancel_ownership_transfer", args)
	if err != nil {
		return fmt.Errorf("failed to call cancel_ownership_transfer: %w", err)
	}

	_ = result // void return
	return nil
}

// SetNewOwner calls the set_new_owner function on the contract.
func (c *RampRegistryClient) SetNewOwner(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_new_owner", args)
	if err != nil {
		return fmt.Errorf("failed to call set_new_owner: %w", err)
	}

	_ = result // void return
	return nil
}

// Initialize calls the initialize function on the contract.
func (c *RampRegistryClient) Initialize(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *RampRegistryClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetOnramp calls the get_onramp function on the contract.
func (c *RampRegistryClient) GetOnramp(ctx context.Context, destChainSelector uint64) (string, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_onramp", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_onramp: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_onramp")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// IsOfframp calls the is_offramp function on the contract.
func (c *RampRegistryClient) IsOfframp(ctx context.Context, sourceChainSelector uint64, offramp string) (bool, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
		scval.AddressToScVal(offramp),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_offramp", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_offramp: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_offramp")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// SetOnramp calls the set_onramp function on the contract.
func (c *RampRegistryClient) SetOnramp(ctx context.Context, destChainSelector uint64, onramp string) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
		scval.AddressToScVal(onramp),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_onramp", args)
	if err != nil {
		return fmt.Errorf("failed to call set_onramp: %w", err)
	}

	_ = result // void return
	return nil
}

// AddOfframp calls the add_offramp function on the contract.
func (c *RampRegistryClient) AddOfframp(ctx context.Context, sourceChainSelector uint64, offramp string) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
		scval.AddressToScVal(offramp),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "add_offramp", args)
	if err != nil {
		return fmt.Errorf("failed to call add_offramp: %w", err)
	}

	_ = result // void return
	return nil
}

// RemoveOfframp calls the remove_offramp function on the contract.
func (c *RampRegistryClient) RemoveOfframp(ctx context.Context, sourceChainSelector uint64, offramp string) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
		scval.AddressToScVal(offramp),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "remove_offramp", args)
	if err != nil {
		return fmt.Errorf("failed to call remove_offramp: %w", err)
	}

	_ = result // void return
	return nil
}

// GetOnramps calls the get_onramps function on the contract.
func (c *RampRegistryClient) GetOnramps(ctx context.Context) ([]OnRampEntry, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_onramps", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_onramps: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_onramps")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]OnRampEntry, len(*vec))
	for i, item := range *vec {
		v, err := OnRampEntryFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// GetOfframps calls the get_offramps function on the contract.
func (c *RampRegistryClient) GetOfframps(ctx context.Context) ([]OffRampEntry, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_offramps", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_offramps: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_offramps")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]OffRampEntry, len(*vec))
	for i, item := range *vec {
		v, err := OffRampEntryFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// ApplyRampUpdates calls the apply_ramp_updates function on the contract.
func (c *RampRegistryClient) ApplyRampUpdates(ctx context.Context, onrampUpdates []OnRampEntry, offrampRemoves []OffRampEntry, offrampAdds []OffRampEntry) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(onrampUpdates),
		scval.StructSliceToScVal(offrampRemoves),
		scval.StructSliceToScVal(offrampAdds),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_ramp_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_ramp_updates: %w", err)
	}

	_ = result // void return
	return nil
}
