// Code generated by stellar-bindings-generator. DO NOT EDIT.
package ramp_registry

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// RampRegistryClient provides methods to interact with the RampRegistry contract.
type RampRegistryClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewRampRegistryClient creates a new RampRegistryClient.
func NewRampRegistryClient(invoker bindings.Invoker, contractID string) *RampRegistryClient {
	return &RampRegistryClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *RampRegistryClient) ContractID() string {
	return c.contractID
}

// Initialize calls the initialize function on the contract.
func (c *RampRegistryClient) Initialize(ctx context.Context, owner string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// TypeAndVersion calls the type_and_version function on the contract.
func (c *RampRegistryClient) TypeAndVersion(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "type_and_version", args)
	if err != nil {
		return "", fmt.Errorf("failed to call type_and_version: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from type_and_version")
	}

	return scval.StringFromScVal(*result)
}

// GetOnramp calls the get_onramp function on the contract.
func (c *RampRegistryClient) GetOnramp(ctx context.Context, destChainSelector uint64) (string, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_onramp", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_onramp: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_onramp")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// IsOfframp calls the is_offramp function on the contract.
func (c *RampRegistryClient) IsOfframp(ctx context.Context, sourceChainSelector uint64, offramp string) (bool, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(sourceChainSelector),
		scval.AddressToScVal(offramp),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_offramp", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_offramp: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_offramp")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// GetOnramps calls the get_onramps function on the contract.
func (c *RampRegistryClient) GetOnramps(ctx context.Context) ([]OnRampEntry, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_onramps", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_onramps: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_onramps")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]OnRampEntry, len(*vec))
	for i, item := range *vec {
		v, err := OnRampEntryFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// GetOfframps calls the get_offramps function on the contract.
func (c *RampRegistryClient) GetOfframps(ctx context.Context) ([]OffRampEntry, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_offramps", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_offramps: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_offramps")
	}

	vec, ok := result.GetVec()
	if !ok || vec == nil {
		return nil, fmt.Errorf("expected vec return type")
	}
	out := make([]OffRampEntry, len(*vec))
	for i, item := range *vec {
		v, err := OffRampEntryFromScVal(item)
		if err != nil {
			return nil, err
		}
		out[i] = *v
	}
	return out, nil
}

// ApplyOnrampUpdates calls the apply_onramp_updates function on the contract.
func (c *RampRegistryClient) ApplyOnrampUpdates(ctx context.Context, updates []OnRampUpdate) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(updates),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_onramp_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_onramp_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// ApplyOfframpUpdates calls the apply_offramp_updates function on the contract.
func (c *RampRegistryClient) ApplyOfframpUpdates(ctx context.Context, updates []OffRampUpdate) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(updates),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_offramp_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_offramp_updates: %w", err)
	}

	_ = result // void return
	return nil
}
