// Code generated by stellar-bindings-generator. DO NOT EDIT.
package onramp

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// OnRampClient provides methods to interact with the OnRamp contract.
type OnRampClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewOnRampClient creates a new OnRampClient.
func NewOnRampClient(invoker bindings.Invoker, contractID string) *OnRampClient {
	return &OnRampClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *OnRampClient) ContractID() string {
	return c.contractID
}

// Owner calls the owner function on the contract.
func (c *OnRampClient) Owner(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "owner", args)
	if err != nil {
		return "", fmt.Errorf("failed to call owner: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from owner")
	}

	v, err := addressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// GetFee calls the get_fee function on the contract.
func (c *OnRampClient) GetFee(ctx context.Context, destChainSelector uint64, message StellarToAnyMessage) (int64, error) {
	args := []xdr.ScVal{
		uint64ToScVal(destChainSelector),
		mustToScVal(message.ToScVal()),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_fee", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_fee: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_fee")
	}

	v, err := i128FromScVal(*result)
	if err != nil {
		return 0, err
	}
	return v, nil
}

// Initialize calls the initialize function on the contract.
func (c *OnRampClient) Initialize(ctx context.Context, owner string, staticConfig StaticConfig, dynamicConfig DynamicConfig) error {
	args := []xdr.ScVal{
		addressToScVal(owner),
		mustToScVal(staticConfig.ToScVal()),
		mustToScVal(dynamicConfig.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// GetStaticConfig calls the get_static_config function on the contract.
func (c *OnRampClient) GetStaticConfig(ctx context.Context) (*StaticConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_static_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_static_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_static_config")
	}

	return StaticConfigFromScVal(*result)
}

// GetDynamicConfig calls the get_dynamic_config function on the contract.
func (c *OnRampClient) GetDynamicConfig(ctx context.Context) (*DynamicConfig, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dynamic_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dynamic_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dynamic_config")
	}

	return DynamicConfigFromScVal(*result)
}

// SetDynamicConfig calls the set_dynamic_config function on the contract.
func (c *OnRampClient) SetDynamicConfig(ctx context.Context, dynamicConfig DynamicConfig) error {
	args := []xdr.ScVal{
		mustToScVal(dynamicConfig.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_dynamic_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_dynamic_config: %w", err)
	}

	_ = result // void return
	return nil
}

// TransferOwnership calls the transfer_ownership function on the contract.
func (c *OnRampClient) TransferOwnership(ctx context.Context, newOwner string) error {
	args := []xdr.ScVal{
		addressToScVal(newOwner),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "transfer_ownership", args)
	if err != nil {
		return fmt.Errorf("failed to call transfer_ownership: %w", err)
	}

	_ = result // void return
	return nil
}

// ForwardFromRouter calls the forward_from_router function on the contract.
func (c *OnRampClient) ForwardFromRouter(ctx context.Context, destChainSelector uint64, message StellarToAnyMessage, feeTokenAmount int64, originalSender string) ([32]byte, error) {
	args := []xdr.ScVal{
		uint64ToScVal(destChainSelector),
		mustToScVal(message.ToScVal()),
		i128ToScVal(feeTokenAmount),
		addressToScVal(originalSender),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "forward_from_router", args)
	if err != nil {
		return [32]byte{}, fmt.Errorf("failed to call forward_from_router: %w", err)
	}

	if result == nil {
		return [32]byte{}, fmt.Errorf("no return value from forward_from_router")
	}

	v, err := bytes32FromScVal(*result)
	if err != nil {
		return [32]byte{}, err
	}
	return v, nil
}

// WithdrawFeeTokens calls the withdraw_fee_tokens function on the contract.
func (c *OnRampClient) WithdrawFeeTokens(ctx context.Context, feeTokens []string) error {
	args := []xdr.ScVal{
		addressSliceToScVal(feeTokens),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "withdraw_fee_tokens", args)
	if err != nil {
		return fmt.Errorf("failed to call withdraw_fee_tokens: %w", err)
	}

	_ = result // void return
	return nil
}

// GetDestChainConfig calls the get_dest_chain_config function on the contract.
func (c *OnRampClient) GetDestChainConfig(ctx context.Context, destChainSelector uint64) (*DestChainConfig, error) {
	args := []xdr.ScVal{
		uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_dest_chain_config", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_dest_chain_config: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_dest_chain_config")
	}

	return DestChainConfigFromScVal(*result)
}

// GetPoolBySourceToken calls the get_pool_by_source_token function on the contract.
func (c *OnRampClient) GetPoolBySourceToken(ctx context.Context, sourceToken string) (string, error) {
	args := []xdr.ScVal{
		addressToScVal(sourceToken),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_pool_by_source_token", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_pool_by_source_token: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_pool_by_source_token")
	}

	v, err := addressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// GetAllDestChainConfigs calls the get_all_dest_chain_configs function on the contract.
func (c *OnRampClient) GetAllDestChainConfigs(ctx context.Context) error {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_all_dest_chain_configs", args)
	if err != nil {
		return fmt.Errorf("failed to call get_all_dest_chain_configs: %w", err)
	}

	_ = result // void return
	return nil
}

// ApplyDestChainConfigUpdates calls the apply_dest_chain_config_updates function on the contract.
func (c *OnRampClient) ApplyDestChainConfigUpdates(ctx context.Context, destChainConfigArgs []DestChainConfigArgs) error {
	args := []xdr.ScVal{
		structSliceToScVal(destChainConfigArgs),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_dest_chain_config_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_dest_chain_config_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// GetExpectedNextMessageNumber calls the get_expected_next_message_number function on the contract.
func (c *OnRampClient) GetExpectedNextMessageNumber(ctx context.Context, destChainSelector uint64) (uint64, error) {
	args := []xdr.ScVal{
		uint64ToScVal(destChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_expected_next_message_number", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_expected_next_message_number: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_expected_next_message_number")
	}

	v, err := uint64FromScVal(*result)
	if err != nil {
		return 0, err
	}
	return v, nil
}

