// Code generated by stellar-bindings-generator. DO NOT EDIT.
package onramp

import (
	"fmt"

	"github.com/stellar/go-stellar-sdk/strkey"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// Receipt represents the Receipt struct from the contract.
type Receipt struct {
	DestBytesOverhead uint32
	DestGasLimit uint32
	ExtraArgs []byte
	FeeTokenAmount int64
	Issuer string
}

// ToScVal converts Receipt to an xdr.ScVal for contract calls.
func (s Receipt) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"dest_bytes_overhead": uint32ToScVal(s.DestBytesOverhead),
		"dest_gas_limit": uint32ToScVal(s.DestGasLimit),
		"extra_args": bytesToScVal(s.ExtraArgs),
		"fee_token_amount": i128ToScVal(s.FeeTokenAmount),
		"issuer": addressToScVal(s.Issuer),
	})
}

// ReceiptFromScVal parses an xdr.ScVal into Receipt.
func ReceiptFromScVal(val xdr.ScVal) (*Receipt, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &Receipt{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_bytes_overhead":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_bytes_overhead is not u32")
			}
			result.DestBytesOverhead = uint32(v)
		case "dest_gas_limit":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("dest_gas_limit is not u32")
			}
			result.DestGasLimit = uint32(v)
		case "extra_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("extra_args is not bytes")
			}
			result.ExtraArgs = []byte(v)
		case "fee_token_amount":
			v, err := i128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token_amount: %w", err)
			}
			result.FeeTokenAmount = v
		case "issuer":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("issuer: %w", err)
			}
			result.Issuer = v
		}
	}

	return result, nil
}

// StaticConfig represents the StaticConfig struct from the contract.
type StaticConfig struct {
	ChainSelector uint64
	MaxUsdCentsPerMessage uint32
	RmnRemote string
	TokenAdminRegistry string
}

// ToScVal converts StaticConfig to an xdr.ScVal for contract calls.
func (s StaticConfig) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"chain_selector": uint64ToScVal(s.ChainSelector),
		"max_usd_cents_per_message": uint32ToScVal(s.MaxUsdCentsPerMessage),
		"rmn_remote": addressToScVal(s.RmnRemote),
		"token_admin_registry": addressToScVal(s.TokenAdminRegistry),
	})
}

// StaticConfigFromScVal parses an xdr.ScVal into StaticConfig.
func StaticConfigFromScVal(val xdr.ScVal) (*StaticConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StaticConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "chain_selector":
			v, err := uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("chain_selector: %w", err)
			}
			result.ChainSelector = v
		case "max_usd_cents_per_message":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("max_usd_cents_per_message is not u32")
			}
			result.MaxUsdCentsPerMessage = uint32(v)
		case "rmn_remote":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("rmn_remote: %w", err)
			}
			result.RmnRemote = v
		case "token_admin_registry":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token_admin_registry: %w", err)
			}
			result.TokenAdminRegistry = v
		}
	}

	return result, nil
}

// DynamicConfig represents the DynamicConfig struct from the contract.
type DynamicConfig struct {
	FeeAggregator string
	FeeQuoter string
}

// ToScVal converts DynamicConfig to an xdr.ScVal for contract calls.
func (s DynamicConfig) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"fee_aggregator": addressToScVal(s.FeeAggregator),
		"fee_quoter": addressToScVal(s.FeeQuoter),
	})
}

// DynamicConfigFromScVal parses an xdr.ScVal into DynamicConfig.
func DynamicConfigFromScVal(val xdr.ScVal) (*DynamicConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &DynamicConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "fee_aggregator":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_aggregator: %w", err)
			}
			result.FeeAggregator = v
		case "fee_quoter":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_quoter: %w", err)
			}
			result.FeeQuoter = v
		}
	}

	return result, nil
}

// DestChainConfig represents the DestChainConfig struct from the contract.
type DestChainConfig struct {
	AddressBytesLength uint32
	BaseExecutionGasCost uint32
	DefaultCcvs []string
	DefaultExecutor string
	LaneMandatedCcvs []string
	MessageNetworkFeeUsdCents uint32
	MessageNumber uint64
	OffRamp []byte
	Router string
	TokenNetworkFeeUsdCents uint32
	TokenReceiverAllowed bool
}

// ToScVal converts DestChainConfig to an xdr.ScVal for contract calls.
func (s DestChainConfig) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"address_bytes_length": uint32ToScVal(s.AddressBytesLength),
		"base_execution_gas_cost": uint32ToScVal(s.BaseExecutionGasCost),
		"default_ccvs": addressSliceToScVal(s.DefaultCcvs),
		"default_executor": addressToScVal(s.DefaultExecutor),
		"lane_mandated_ccvs": addressSliceToScVal(s.LaneMandatedCcvs),
		"message_network_fee_usd_cents": uint32ToScVal(s.MessageNetworkFeeUsdCents),
		"message_number": uint64ToScVal(s.MessageNumber),
		"off_ramp": bytesToScVal(s.OffRamp),
		"router": addressToScVal(s.Router),
		"token_network_fee_usd_cents": uint32ToScVal(s.TokenNetworkFeeUsdCents),
		"token_receiver_allowed": boolToScVal(s.TokenReceiverAllowed),
	})
}

// DestChainConfigFromScVal parses an xdr.ScVal into DestChainConfig.
func DestChainConfigFromScVal(val xdr.ScVal) (*DestChainConfig, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &DestChainConfig{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "address_bytes_length":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("address_bytes_length is not u32")
			}
			result.AddressBytesLength = uint32(v)
		case "base_execution_gas_cost":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("base_execution_gas_cost is not u32")
			}
			result.BaseExecutionGasCost = uint32(v)
		case "default_ccvs":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("default_ccvs is not a vec")
			}
			result.DefaultCcvs = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := addressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.DefaultCcvs[i] = v
			}
		case "default_executor":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("default_executor: %w", err)
			}
			result.DefaultExecutor = v
		case "lane_mandated_ccvs":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("lane_mandated_ccvs is not a vec")
			}
			result.LaneMandatedCcvs = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := addressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.LaneMandatedCcvs[i] = v
			}
		case "message_network_fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("message_network_fee_usd_cents is not u32")
			}
			result.MessageNetworkFeeUsdCents = uint32(v)
		case "message_number":
			v, err := uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("message_number: %w", err)
			}
			result.MessageNumber = v
		case "off_ramp":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("off_ramp is not bytes")
			}
			result.OffRamp = []byte(v)
		case "router":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("router: %w", err)
			}
			result.Router = v
		case "token_network_fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("token_network_fee_usd_cents is not u32")
			}
			result.TokenNetworkFeeUsdCents = uint32(v)
		case "token_receiver_allowed":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("token_receiver_allowed is not bool")
			}
			result.TokenReceiverAllowed = v
		}
	}

	return result, nil
}

// DestChainConfigArgs represents the DestChainConfigArgs struct from the contract.
type DestChainConfigArgs struct {
	AddressBytesLength uint32
	BaseExecutionGasCost uint32
	DefaultCcvs []string
	DefaultExecutor string
	DestChainSelector uint64
	LaneMandatedCcvs []string
	MessageNetworkFeeUsdCents uint32
	OffRamp []byte
	Router string
	TokenNetworkFeeUsdCents uint32
	TokenReceiverAllowed bool
}

// ToScVal converts DestChainConfigArgs to an xdr.ScVal for contract calls.
func (s DestChainConfigArgs) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"address_bytes_length": uint32ToScVal(s.AddressBytesLength),
		"base_execution_gas_cost": uint32ToScVal(s.BaseExecutionGasCost),
		"default_ccvs": addressSliceToScVal(s.DefaultCcvs),
		"default_executor": addressToScVal(s.DefaultExecutor),
		"dest_chain_selector": uint64ToScVal(s.DestChainSelector),
		"lane_mandated_ccvs": addressSliceToScVal(s.LaneMandatedCcvs),
		"message_network_fee_usd_cents": uint32ToScVal(s.MessageNetworkFeeUsdCents),
		"off_ramp": bytesToScVal(s.OffRamp),
		"router": addressToScVal(s.Router),
		"token_network_fee_usd_cents": uint32ToScVal(s.TokenNetworkFeeUsdCents),
		"token_receiver_allowed": boolToScVal(s.TokenReceiverAllowed),
	})
}

// DestChainConfigArgsFromScVal parses an xdr.ScVal into DestChainConfigArgs.
func DestChainConfigArgsFromScVal(val xdr.ScVal) (*DestChainConfigArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &DestChainConfigArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "address_bytes_length":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("address_bytes_length is not u32")
			}
			result.AddressBytesLength = uint32(v)
		case "base_execution_gas_cost":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("base_execution_gas_cost is not u32")
			}
			result.BaseExecutionGasCost = uint32(v)
		case "default_ccvs":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("default_ccvs is not a vec")
			}
			result.DefaultCcvs = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := addressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.DefaultCcvs[i] = v
			}
		case "default_executor":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("default_executor: %w", err)
			}
			result.DefaultExecutor = v
		case "dest_chain_selector":
			v, err := uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "lane_mandated_ccvs":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("lane_mandated_ccvs is not a vec")
			}
			result.LaneMandatedCcvs = make([]string, len(*vec))
			for i, item := range *vec {
				v, err := addressFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.LaneMandatedCcvs[i] = v
			}
		case "message_network_fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("message_network_fee_usd_cents is not u32")
			}
			result.MessageNetworkFeeUsdCents = uint32(v)
		case "off_ramp":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("off_ramp is not bytes")
			}
			result.OffRamp = []byte(v)
		case "router":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("router: %w", err)
			}
			result.Router = v
		case "token_network_fee_usd_cents":
			v, ok := entry.Val.GetU32()
			if !ok {
				return nil, fmt.Errorf("token_network_fee_usd_cents is not u32")
			}
			result.TokenNetworkFeeUsdCents = uint32(v)
		case "token_receiver_allowed":
			v, ok := entry.Val.GetB()
			if !ok {
				return nil, fmt.Errorf("token_receiver_allowed is not bool")
			}
			result.TokenReceiverAllowed = v
		}
	}

	return result, nil
}

// TokenAmount represents the TokenAmount struct from the contract.
type TokenAmount struct {
	Amount int64
	Token string
}

// ToScVal converts TokenAmount to an xdr.ScVal for contract calls.
func (s TokenAmount) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"amount": i128ToScVal(s.Amount),
		"token": addressToScVal(s.Token),
	})
}

// TokenAmountFromScVal parses an xdr.ScVal into TokenAmount.
func TokenAmountFromScVal(val xdr.ScVal) (*TokenAmount, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &TokenAmount{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "amount":
			v, err := i128FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("amount: %w", err)
			}
			result.Amount = v
		case "token":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("token: %w", err)
			}
			result.Token = v
		}
	}

	return result, nil
}

// AnyToStellarMessage represents the AnyToStellarMessage struct from the contract.
type AnyToStellarMessage struct {
	Placeholder uint64
}

// ToScVal converts AnyToStellarMessage to an xdr.ScVal for contract calls.
func (s AnyToStellarMessage) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"placeholder": uint64ToScVal(s.Placeholder),
	})
}

// AnyToStellarMessageFromScVal parses an xdr.ScVal into AnyToStellarMessage.
func AnyToStellarMessageFromScVal(val xdr.ScVal) (*AnyToStellarMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &AnyToStellarMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "placeholder":
			v, err := uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("placeholder: %w", err)
			}
			result.Placeholder = v
		}
	}

	return result, nil
}

// StellarToAnyMessage represents the StellarToAnyMessage struct from the contract.
type StellarToAnyMessage struct {
	Data []byte
	ExtraArgs []byte
	FeeToken string
	Receiver []byte
	TokenAmounts []TokenAmount
}

// ToScVal converts StellarToAnyMessage to an xdr.ScVal for contract calls.
func (s StellarToAnyMessage) ToScVal() (xdr.ScVal, error) {
	return buildStructScVal(map[string]xdr.ScVal{
		"data": bytesToScVal(s.Data),
		"extra_args": bytesToScVal(s.ExtraArgs),
		"fee_token": addressToScVal(s.FeeToken),
		"receiver": bytesToScVal(s.Receiver),
		"token_amounts": structSliceToScVal(s.TokenAmounts),
	})
}

// StellarToAnyMessageFromScVal parses an xdr.ScVal into StellarToAnyMessage.
func StellarToAnyMessageFromScVal(val xdr.ScVal) (*StellarToAnyMessage, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &StellarToAnyMessage{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "data":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("data is not bytes")
			}
			result.Data = []byte(v)
		case "extra_args":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("extra_args is not bytes")
			}
			result.ExtraArgs = []byte(v)
		case "fee_token":
			v, err := addressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("fee_token: %w", err)
			}
			result.FeeToken = v
		case "receiver":
			v, ok := entry.Val.GetBytes()
			if !ok {
				return nil, fmt.Errorf("receiver is not bytes")
			}
			result.Receiver = []byte(v)
		case "token_amounts":
			vec, ok := entry.Val.GetVec()
			if !ok || vec == nil {
				return nil, fmt.Errorf("token_amounts is not a vec")
			}
			result.TokenAmounts = make([]TokenAmount, len(*vec))
			for i, item := range *vec {
				v, err := TokenAmountFromScVal(item)
				if err != nil {
					return nil, err
				}
				result.TokenAmounts[i] = *v
			}
		}
	}

	return result, nil
}

// OnRampError represents the contract error codes.
const (
	OnRampErrorAlreadyInitialized = 1
	OnRampErrorNotInitialized = 2
	OnRampErrorUnauthorized = 3
	OnRampErrorInvalidConfig = 4
	OnRampErrorDestinationChainNotSupported = 5
	OnRampErrorMustBeCalledByRouter = 6
	OnRampErrorRouterMustSetOriginalSender = 7
	OnRampErrorCannotSendZeroTokens = 8
	OnRampErrorCanOnlySendOneTokenPerMessage = 9
	OnRampErrorUnsupportedToken = 10
	OnRampErrorInvalidDestChainAddress = 11
	OnRampErrorFeeExceedsMaxAllowed = 12
	OnRampErrorInsufficientFeeTokenAmount = 13
	OnRampErrorReentrancyGuardReentrantCall = 14
	OnRampErrorDestinationChainNotSupportedByCCV = 15
	OnRampErrorTokenReceiverNotAllowed = 16
	OnRampErrorSourceTokenDataTooLarge = 17
	OnRampErrorCursedByRMN = 18
	OnRampErrorInvalidTokenAmount = 19
	OnRampErrorInvalidReceiverAddress = 20
)

// OnRampErrorMessage returns a human-readable message for error codes.
var OnRampErrorMessage = map[int]string{
	1: "already initialized",
	2: "not initialized",
	3: "unauthorized",
	4: "invalid config",
	5: "destination chain not supported",
	6: "must be called by router",
	7: "router must set original sender",
	8: "cannot send zero tokens",
	9: "can only send one token per message",
	10: "unsupported token",
	11: "invalid dest chain address",
	12: "fee exceeds max allowed",
	13: "insufficient fee token amount",
	14: "reentrancy guard reentrant call",
	15: "destination chain not supported by c c v",
	16: "token receiver not allowed",
	17: "source token data too large",
	18: "cursed by r m n",
	19: "invalid token amount",
	20: "invalid receiver address",
}

// GuardError represents the contract error codes.
const (
	GuardErrorReentrantCall = 1
)

// GuardErrorMessage returns a human-readable message for error codes.
var GuardErrorMessage = map[int]string{
	1: "reentrant call",
}

// Helper functions for ScVal conversions

func uint64ToScVal(v uint64) xdr.ScVal {
	xdrU64 := xdr.Uint64(v)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvU64,
		U64:  &xdrU64,
	}
}

func uint32ToScVal(v uint32) xdr.ScVal {
	xdrU32 := xdr.Uint32(v)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvU32,
		U32:  &xdrU32,
	}
}

func boolToScVal(v bool) xdr.ScVal {
	return xdr.ScVal{
		Type: xdr.ScValTypeScvBool,
		B:    &v,
	}
}

func i128ToScVal(v int64) xdr.ScVal {
	var hi int64
	if v < 0 {
		hi = -1 // Sign extend for negative numbers
	}
	lo := uint64(v)
	parts := xdr.Int128Parts{
		Hi: xdr.Int64(hi),
		Lo: xdr.Uint64(lo),
	}
	return xdr.ScVal{
		Type: xdr.ScValTypeScvI128,
		I128: &parts,
	}
}

func bytesToScVal(b []byte) xdr.ScVal {
	bytes := xdr.ScBytes(b)
	return xdr.ScVal{
		Type:  xdr.ScValTypeScvBytes,
		Bytes: &bytes,
	}
}

func bytes32ToScVal(b [32]byte) xdr.ScVal {
	bytes := xdr.ScBytes(b[:])
	return xdr.ScVal{
		Type:  xdr.ScValTypeScvBytes,
		Bytes: &bytes,
	}
}

func addressToScVal(addr string) xdr.ScVal {
	scAddr := parseAddress(addr)
	return xdr.ScVal{
		Type:    xdr.ScValTypeScvAddress,
		Address: scAddr,
	}
}

func vecToScVal(items []xdr.ScVal) xdr.ScVal {
	scVec := xdr.ScVec(items)
	vecPtr := &scVec
	return xdr.ScVal{
		Type: xdr.ScValTypeScvVec,
		Vec:  &vecPtr,
	}
}

func symbolToScVal(sym string) xdr.ScVal {
	scSym := xdr.ScSymbol(sym)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvSymbol,
		Sym:  &scSym,
	}
}

func buildStructScVal(fields map[string]xdr.ScVal) (xdr.ScVal, error) {
	entries := make([]xdr.ScMapEntry, 0, len(fields))
	for k, v := range fields {
		sym := xdr.ScSymbol(k)
		entries = append(entries, xdr.ScMapEntry{
			Key: xdr.ScVal{
				Type: xdr.ScValTypeScvSymbol,
				Sym:  &sym,
			},
			Val: v,
		})
	}
	scMap := xdr.ScMap(entries)
	mapPtr := &scMap
	return xdr.ScVal{
		Type: xdr.ScValTypeScvMap,
		Map:  &mapPtr,
	}, nil
}

func parseAddress(addr string) *xdr.ScAddress {
	if len(addr) == 0 {
		return nil
	}

	if addr[0] == 'C' {
		decoded, err := strkey.Decode(strkey.VersionByteContract, addr)
		if err != nil {
			return nil
		}
		return buildContractScAddress(decoded)
	}

	if addr[0] == 'G' {
		decoded, err := strkey.Decode(strkey.VersionByteAccountID, addr)
		if err != nil {
			return nil
		}
		var pubKey xdr.Uint256
		copy(pubKey[:], decoded)
		accountID := xdr.AccountId{
			Type:    xdr.PublicKeyTypePublicKeyTypeEd25519,
			Ed25519: &pubKey,
		}
		return &xdr.ScAddress{
			Type:      xdr.ScAddressTypeScAddressTypeAccount,
			AccountId: &accountID,
		}
	}

	return nil
}

func buildContractScAddress(contractIDBytes []byte) *xdr.ScAddress {
	if len(contractIDBytes) != 32 {
		return nil
	}
	xdrBytes := make([]byte, 0, 36)
	xdrBytes = append(xdrBytes, 0, 0, 0, 1)
	xdrBytes = append(xdrBytes, contractIDBytes...)

	var addr xdr.ScAddress
	if err := addr.UnmarshalBinary(xdrBytes); err != nil {
		return nil
	}
	return &addr
}

func addressFromScVal(val xdr.ScVal) (string, error) {
	addr, ok := val.GetAddress()
	if !ok {
		return "", fmt.Errorf("not an address type: %v", val.Type)
	}

	switch addr.Type {
	case xdr.ScAddressTypeScAddressTypeAccount:
		accountID := addr.MustAccountId()
		pubKey := accountID.Ed25519
		if pubKey == nil {
			return "", fmt.Errorf("account ID has no Ed25519 key")
		}
		return strkey.Encode(strkey.VersionByteAccountID, (*pubKey)[:])
	case xdr.ScAddressTypeScAddressTypeContract:
		contractID := addr.MustContractId()
		return strkey.Encode(strkey.VersionByteContract, contractID[:])
	default:
		return "", fmt.Errorf("unsupported address type: %s", addr.Type)
	}
}

func uint64FromScVal(val xdr.ScVal) (uint64, error) {
	u64, ok := val.GetU64()
	if !ok {
		return 0, fmt.Errorf("not a u64 type: %v", val.Type)
	}
	return uint64(u64), nil
}

func bytes32FromScVal(val xdr.ScVal) ([32]byte, error) {
	bytes, ok := val.GetBytes()
	if !ok {
		return [32]byte{}, fmt.Errorf("not a bytes type: %v", val.Type)
	}
	if len(bytes) != 32 {
		return [32]byte{}, fmt.Errorf("expected 32 bytes, got %d", len(bytes))
	}
	var result [32]byte
	copy(result[:], bytes)
	return result, nil
}

func i128FromScVal(val xdr.ScVal) (int64, error) {
	i128, ok := val.GetI128()
	if !ok {
		return 0, fmt.Errorf("not an i128 type: %v", val.Type)
	}
	return int64(i128.Lo), nil
}

// mustToScVal panics if ToScVal returns an error.
func mustToScVal(val xdr.ScVal, err error) xdr.ScVal {
	if err != nil {
		panic(err)
	}
	return val
}

// addressSliceToScVal converts a slice of address strings to xdr.ScVal.
func addressSliceToScVal(items []string) xdr.ScVal {
	scVals := make([]xdr.ScVal, len(items))
	for i, item := range items {
		scVals[i] = addressToScVal(item)
	}
	return vecToScVal(scVals)
}

// structSliceToScVal converts a slice of structs with ToScVal to xdr.ScVal.
func structSliceToScVal[T interface{ ToScVal() (xdr.ScVal, error) }](items []T) xdr.ScVal {
	scVals := make([]xdr.ScVal, len(items))
	for i := range items {
		val, err := items[i].ToScVal()
		if err != nil {
			panic(err)
		}
		scVals[i] = val
	}
	return vecToScVal(scVals)
}
