// Code generated by stellar-bindings-generator. DO NOT EDIT.
package burn_mint_pool

import (
	"context"
	"fmt"
	"time"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	protocolrpc "github.com/stellar/go-stellar-sdk/protocols/rpc"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// BurnMintPoolClient provides methods to interact with the BurnMintPool contract.
type BurnMintPoolClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewBurnMintPoolClient creates a new BurnMintPoolClient.
func NewBurnMintPoolClient(invoker bindings.Invoker, contractID string) *BurnMintPoolClient {
	return &BurnMintPoolClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *BurnMintPoolClient) ContractID() string {
	return c.contractID
}

// Initialize calls the initialize function on the contract.
func (c *BurnMintPoolClient) Initialize(ctx context.Context, owner string, token string, tokenDecimals uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.AddressToScVal(token),
		scval.Uint32ToScVal(tokenDecimals),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// LockOrBurn calls the lock_or_burn function on the contract.
func (c *BurnMintPoolClient) LockOrBurn(ctx context.Context, input LockOrBurnIn, requestedFinality uint32) (*LockOrBurnOut, error) {
	args := []xdr.ScVal{
		scval.MustToScVal(input.ToScVal()),
		scval.Uint32ToScVal(requestedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "lock_or_burn", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call lock_or_burn: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from lock_or_burn")
	}

	return LockOrBurnOutFromScVal(*result)
}

// ReleaseOrMint calls the release_or_mint function on the contract.
func (c *BurnMintPoolClient) ReleaseOrMint(ctx context.Context, input ReleaseOrMintIn, requestedFinality uint32) (*ReleaseOrMintOut, error) {
	args := []xdr.ScVal{
		scval.MustToScVal(input.ToScVal()),
		scval.Uint32ToScVal(requestedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "release_or_mint", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call release_or_mint: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from release_or_mint")
	}

	return ReleaseOrMintOutFromScVal(*result)
}

// GetFee calls the get_fee function on the contract.
func (c *BurnMintPoolClient) GetFee(ctx context.Context, remoteChainSelector uint64) (*PoolFeeResult, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_fee", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_fee: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_fee")
	}

	return PoolFeeResultFromScVal(*result)
}

// IsSupportedToken calls the is_supported_token function on the contract.
func (c *BurnMintPoolClient) IsSupportedToken(ctx context.Context, token string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_token", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_token: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_token")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// IsSupportedChain calls the is_supported_chain function on the contract.
func (c *BurnMintPoolClient) IsSupportedChain(ctx context.Context, remoteChainSelector uint64) (bool, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_chain", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_chain: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_chain")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// GetToken calls the get_token function on the contract.
func (c *BurnMintPoolClient) GetToken(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_token: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_token")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// GetTokenDecimals calls the get_token_decimals function on the contract.
func (c *BurnMintPoolClient) GetTokenDecimals(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_decimals", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_token_decimals: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_token_decimals")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// GetRemotePool calls the get_remote_pool function on the contract.
func (c *BurnMintPoolClient) GetRemotePool(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_pool", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_pool: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_pool")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// GetRemoteToken calls the get_remote_token function on the contract.
func (c *BurnMintPoolClient) GetRemoteToken(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_token", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_token: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_token")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// ApplyChainUpdates calls the apply_chain_updates function on the contract.
func (c *BurnMintPoolClient) ApplyChainUpdates(ctx context.Context, adds []ChainUpdate, removes []uint64) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(adds),
		scval.Uint64SliceToScVal(removes),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_chain_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_chain_updates: %w", err)
	}

	_ = result // void return
	return nil
}

// SetRateLimitConfig calls the set_rate_limit_config function on the contract.
func (c *BurnMintPoolClient) SetRateLimitConfig(ctx context.Context, remoteChainSelector uint64, outboundConfig RateLimitConfig, inboundConfig RateLimitConfig, fastFinality bool) error {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
		scval.MustToScVal(outboundConfig.ToScVal()),
		scval.MustToScVal(inboundConfig.ToScVal()),
		scval.BoolToScVal(fastFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_rate_limit_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_rate_limit_config: %w", err)
	}

	_ = result // void return
	return nil
}

// SetRateLimitAdmin calls the set_rate_limit_admin function on the contract.
func (c *BurnMintPoolClient) SetRateLimitAdmin(ctx context.Context, admin string) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(admin),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_rate_limit_admin", args)
	if err != nil {
		return fmt.Errorf("failed to call set_rate_limit_admin: %w", err)
	}

	_ = result // void return
	return nil
}

// GetCurrentRateLimiterState calls the get_current_rate_limiter_state function on the contract.
func (c *BurnMintPoolClient) GetCurrentRateLimiterState(ctx context.Context, remoteChainSelector uint64, fastFinality bool) (*RateLimiterState, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
		scval.BoolToScVal(fastFinality),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_current_rate_limiter_state", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_current_rate_limiter_state: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_current_rate_limiter_state")
	}

	return RateLimiterStateFromScVal(*result)
}

// GetRateLimitAdmin calls the get_rate_limit_admin function on the contract.
func (c *BurnMintPoolClient) GetRateLimitAdmin(ctx context.Context) (*string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_rate_limit_admin", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_rate_limit_admin: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_rate_limit_admin")
	}

	v, err := scval.OptionalAddressFromScVal(*result)
	if err != nil {
		return nil, err
	}
	return v, nil
}

// SetAllowedFinalityConfig calls the set_allowed_finality_config function on the contract.
func (c *BurnMintPoolClient) SetAllowedFinalityConfig(ctx context.Context, allowedFinality uint32) error {
	args := []xdr.ScVal{
		scval.Uint32ToScVal(allowedFinality),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "set_allowed_finality_config", args)
	if err != nil {
		return fmt.Errorf("failed to call set_allowed_finality_config: %w", err)
	}

	_ = result // void return
	return nil
}

// GetAllowedFinalityConfig calls the get_allowed_finality_config function on the contract.
func (c *BurnMintPoolClient) GetAllowedFinalityConfig(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_allowed_finality_config", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_allowed_finality_config: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_allowed_finality_config")
	}

	v, ok := result.GetU32()
	if !ok {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(v), nil
}

// WaitForLockedEvent waits for a LockedEvent event.
func (c *BurnMintPoolClient) WaitForLockedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*LockedEvent) bool) (*LockedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{LockedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseLockedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseLockedEvent(e protocolrpc.EventInfo) (*LockedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &LockedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForReleasedEvent waits for a ReleasedEvent event.
func (c *BurnMintPoolClient) WaitForReleasedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ReleasedEvent) bool) (*ReleasedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ReleasedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseReleasedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseReleasedEvent(e protocolrpc.EventInfo) (*ReleasedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ReleasedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "recipient":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Recipient = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForBurnedEvent waits for a BurnedEvent event.
func (c *BurnMintPoolClient) WaitForBurnedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*BurnedEvent) bool) (*BurnedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{BurnedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseBurnedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseBurnedEvent(e protocolrpc.EventInfo) (*BurnedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &BurnedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForMintedEvent waits for a MintedEvent event.
func (c *BurnMintPoolClient) WaitForMintedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*MintedEvent) bool) (*MintedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{MintedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseMintedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseMintedEvent(e protocolrpc.EventInfo) (*MintedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &MintedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "sender":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Sender = v
			}
		case "recipient":
			v, err := scval.AddressFromScVal(entry.Val)
			if err == nil {
				result.Recipient = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForChainConfiguredEvent waits for a ChainConfiguredEvent event.
func (c *BurnMintPoolClient) WaitForChainConfiguredEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ChainConfiguredEvent) bool) (*ChainConfiguredEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ChainConfiguredEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseChainConfiguredEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseChainConfiguredEvent(e protocolrpc.EventInfo) (*ChainConfiguredEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ChainConfiguredEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "remote_pool_address":
			v, ok := entry.Val.GetBytes()
			if ok {
				result.RemotePoolAddress = []byte(v)
			}
		case "remote_token_address":
			v, ok := entry.Val.GetBytes()
			if ok {
				result.RemoteTokenAddress = []byte(v)
			}
		case "outbound_rate_limiter_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.OutboundRateLimiterConfig = *v
			}
		case "inbound_rate_limiter_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.InboundRateLimiterConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForChainRemovedEvent waits for a ChainRemovedEvent event.
func (c *BurnMintPoolClient) WaitForChainRemovedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*ChainRemovedEvent) bool) (*ChainRemovedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{ChainRemovedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseChainRemovedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseChainRemovedEvent(e protocolrpc.EventInfo) (*ChainRemovedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &ChainRemovedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		}
	}

	return result, nil
}

// WaitForRateLimitConfiguredEvent waits for a RateLimitConfiguredEvent event.
func (c *BurnMintPoolClient) WaitForRateLimitConfiguredEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*RateLimitConfiguredEvent) bool) (*RateLimitConfiguredEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{RateLimitConfiguredEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseRateLimitConfiguredEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseRateLimitConfiguredEvent(e protocolrpc.EventInfo) (*RateLimitConfiguredEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &RateLimitConfiguredEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "fast_finality":
			v, ok := entry.Val.GetB()
			if ok {
				result.FastFinality = v
			}
		case "outbound_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.OutboundConfig = *v
			}
		case "inbound_config":
			v, err := RateLimitConfigFromScVal(entry.Val)
			if err == nil {
				result.InboundConfig = *v
			}
		}
	}

	return result, nil
}

// WaitForOutboundRateLimitConsumedEvent waits for a OutboundRateLimitConsumedEvent event.
func (c *BurnMintPoolClient) WaitForOutboundRateLimitConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*OutboundRateLimitConsumedEvent) bool) (*OutboundRateLimitConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{OutboundRateLimitConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseOutboundRateLimitConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseOutboundRateLimitConsumedEvent(e protocolrpc.EventInfo) (*OutboundRateLimitConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &OutboundRateLimitConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForInboundRateLimitConsumedEvent waits for a InboundRateLimitConsumedEvent event.
func (c *BurnMintPoolClient) WaitForInboundRateLimitConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*InboundRateLimitConsumedEvent) bool) (*InboundRateLimitConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{InboundRateLimitConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseInboundRateLimitConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseInboundRateLimitConsumedEvent(e protocolrpc.EventInfo) (*InboundRateLimitConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &InboundRateLimitConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForFtfOutboundConsumedEvent waits for a FtfOutboundConsumedEvent event.
func (c *BurnMintPoolClient) WaitForFtfOutboundConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FtfOutboundConsumedEvent) bool) (*FtfOutboundConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FtfOutboundConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFtfOutboundConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFtfOutboundConsumedEvent(e protocolrpc.EventInfo) (*FtfOutboundConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FtfOutboundConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForFtfInboundConsumedEvent waits for a FtfInboundConsumedEvent event.
func (c *BurnMintPoolClient) WaitForFtfInboundConsumedEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FtfInboundConsumedEvent) bool) (*FtfInboundConsumedEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FtfInboundConsumedEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFtfInboundConsumedEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFtfInboundConsumedEvent(e protocolrpc.EventInfo) (*FtfInboundConsumedEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FtfInboundConsumedEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "remote_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err == nil {
				result.RemoteChainSelector = v
			}
		case "amount":
			v, err := scval.I128FromScVal(entry.Val)
			if err == nil {
				result.Amount = v
			}
		}
	}

	return result, nil
}

// WaitForFinalityConfigSetEvent waits for a FinalityConfigSetEvent event.
func (c *BurnMintPoolClient) WaitForFinalityConfigSetEvent(ctx context.Context, startLedger uint32, timeout time.Duration, filter func(*FinalityConfigSetEvent) bool) (*FinalityConfigSetEvent, error) {
	startTime := time.Now()
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-ticker.C:
			if time.Since(startTime) > timeout {
				return nil, fmt.Errorf("timeout waiting for event")
			}

			events, err := c.invoker.GetEvents(ctx, c.contractID, startLedger, []string{FinalityConfigSetEventTopic})
			if err != nil {
				continue
			}

			for _, e := range events {
				parsed, err := ParseFinalityConfigSetEvent(e)
				if err != nil {
					continue
				}
				if filter == nil || filter(parsed) {
					return parsed, nil
				}
			}
		}
	}
}

func ParseFinalityConfigSetEvent(e protocolrpc.EventInfo) (*FinalityConfigSetEvent, error) {
	var eventVal xdr.ScVal
	if err := xdr.SafeUnmarshalBase64(e.ValueXDR, &eventVal); err != nil {
		return nil, fmt.Errorf("failed to decode event: %w", err)
	}

	scMap, ok := eventVal.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("event is not a map")
	}

	result := &FinalityConfigSetEvent{
		Ledger: uint32(e.Ledger),
		TxHash: e.TransactionHash,
	}

	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "allowed_finality":
			v, ok := entry.Val.GetU32()
			if ok {
				result.AllowedFinality = uint32(v)
			}
		}
	}

	return result, nil
}
