package main

import (
	"fmt"
	"strings"
	"unicode"
)

// GenerateTypes generates the types.go file content.
func GenerateTypes(pkg string, contract *Contract) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// Code generated by stellar-bindings-generator. DO NOT EDIT.\n"))
	b.WriteString(fmt.Sprintf("package %s\n\n", pkg))

	// Imports
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"sort\"\n\n")
	b.WriteString("\t\"github.com/stellar/go-stellar-sdk/strkey\"\n")
	b.WriteString("\t\"github.com/stellar/go-stellar-sdk/xdr\"\n")
	b.WriteString(")\n\n")

	// Generate structs
	for _, s := range contract.Structs {
		generateStruct(&b, s)
	}

	// Generate error enums
	for _, e := range contract.Errors {
		generateErrorEnum(&b, e)
	}

	// Generate events
	for _, e := range contract.Events {
		generateEventStruct(&b, e)
	}

	// Generate helper functions
	generateHelpers(&b)

	return b.String()
}

func generateStruct(b *strings.Builder, s Struct) {
	// Go struct
	b.WriteString(fmt.Sprintf("// %s represents the %s struct from the contract.\n", s.Name, s.Name))
	b.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
	for _, f := range s.Fields {
		goType := rustTypeToGo(f.Type)
		b.WriteString(fmt.Sprintf("\t%s %s\n", snakeToPascal(f.Name), goType))
	}
	b.WriteString("}\n\n")

	// ToScVal method - use value receiver for generics compatibility
	b.WriteString(fmt.Sprintf("// ToScVal converts %s to an xdr.ScVal for contract calls.\n", s.Name))
	b.WriteString(fmt.Sprintf("func (s %s) ToScVal() (xdr.ScVal, error) {\n", s.Name))
	b.WriteString("\treturn buildStructScVal(map[string]xdr.ScVal{\n")
	for _, f := range s.Fields {
		converter := getToScValConverter(f.Type, "s."+snakeToPascal(f.Name))
		b.WriteString(fmt.Sprintf("\t\t\"%s\": %s,\n", f.Name, converter))
	}
	b.WriteString("\t})\n")
	b.WriteString("}\n\n")

	// FromScVal function
	b.WriteString(fmt.Sprintf("// %sFromScVal parses an xdr.ScVal into %s.\n", s.Name, s.Name))
	b.WriteString(fmt.Sprintf("func %sFromScVal(val xdr.ScVal) (*%s, error) {\n", s.Name, s.Name))
	b.WriteString("\tscMap, ok := val.GetMap()\n")
	b.WriteString("\tif !ok || scMap == nil {\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"not a map type\")\n")
	b.WriteString("\t}\n\n")
	b.WriteString(fmt.Sprintf("\tresult := &%s{}\n", s.Name))
	b.WriteString("\tfor _, entry := range *scMap {\n")
	b.WriteString("\t\tkey, ok := entry.Key.GetSym()\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\tcontinue\n")
	b.WriteString("\t\t}\n\n")
	b.WriteString("\t\tswitch string(key) {\n")
	for _, f := range s.Fields {
		b.WriteString(fmt.Sprintf("\t\tcase \"%s\":\n", f.Name))
		generateFromScValField(b, f, "result."+snakeToPascal(f.Name))
	}
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\treturn result, nil\n")
	b.WriteString("}\n\n")
}

func generateFromScValField(b *strings.Builder, f Field, target string) {
	switch {
	case f.Type == "u64":
		b.WriteString(fmt.Sprintf("\t\t\tv, err := uint64FromScVal(entry.Val)\n"))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "u32":
		b.WriteString("\t\t\tv, ok := entry.Val.GetU32()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not u32\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = uint32(v)\n", target))
	case f.Type == "i128":
		b.WriteString("\t\t\tv, err := i128FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "bool":
		b.WriteString("\t\t\tv, ok := entry.Val.GetB()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not bool\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "soroban_sdk::Address":
		b.WriteString("\t\t\tv, err := addressFromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case f.Type == "soroban_sdk::Bytes":
		b.WriteString("\t\t\tv, ok := entry.Val.GetBytes()\n")
		b.WriteString("\t\t\tif !ok {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not bytes\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = []byte(v)\n", target))
	case strings.HasPrefix(f.Type, "soroban_sdk::BytesN<"):
		b.WriteString("\t\t\tv, err := bytes32FromScVal(entry.Val)\n")
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = v\n", target))
	case strings.HasPrefix(f.Type, "soroban_sdk::Vec<"):
		innerType := extractVecInnerType(f.Type)
		b.WriteString("\t\t\tvec, ok := entry.Val.GetVec()\n")
		b.WriteString("\t\t\tif !ok || vec == nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s is not a vec\")\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = make(%s, len(*vec))\n", target, rustTypeToGo(f.Type)))
		b.WriteString("\t\t\tfor i, item := range *vec {\n")
		generateVecItemParse(b, innerType, target+"[i]")
		b.WriteString("\t\t\t}\n")
	default:
		// Nested struct
		structName := extractStructName(f.Type)
		b.WriteString(fmt.Sprintf("\t\t\tv, err := %sFromScVal(entry.Val)\n", structName))
		b.WriteString("\t\t\tif err != nil {\n")
		b.WriteString(fmt.Sprintf("\t\t\t\treturn nil, fmt.Errorf(\"%s: %%w\", err)\n", f.Name))
		b.WriteString("\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t%s = *v\n", target))
	}
}

func generateVecItemParse(b *strings.Builder, innerType, target string) {
	switch innerType {
	case "soroban_sdk::Address":
		b.WriteString("\t\t\t\tv, err := addressFromScVal(item)\n")
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\treturn nil, err\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = v\n", target))
	default:
		// Nested struct in vec
		structName := extractStructName(innerType)
		b.WriteString(fmt.Sprintf("\t\t\t\tv, err := %sFromScVal(item)\n", structName))
		b.WriteString("\t\t\t\tif err != nil {\n")
		b.WriteString("\t\t\t\t\treturn nil, err\n")
		b.WriteString("\t\t\t\t}\n")
		b.WriteString(fmt.Sprintf("\t\t\t\t%s = *v\n", target))
	}
}

func generateErrorEnum(b *strings.Builder, e ErrorEnum) {
	b.WriteString(fmt.Sprintf("// %s represents the contract error codes.\n", e.Name))
	b.WriteString("const (\n")
	for _, v := range e.Variants {
		b.WriteString(fmt.Sprintf("\t%s%s = %d\n", e.Name, v.Name, v.Value))
	}
	b.WriteString(")\n\n")

	// Error message map
	b.WriteString(fmt.Sprintf("// %sMessage returns a human-readable message for error codes.\n", e.Name))
	b.WriteString(fmt.Sprintf("var %sMessage = map[int]string{\n", e.Name))
	for _, v := range e.Variants {
		b.WriteString(fmt.Sprintf("\t%d: \"%s\",\n", v.Value, camelToSpaces(v.Name)))
	}
	b.WriteString("}\n\n")
}

func generateEventStruct(b *strings.Builder, e Event) {
	b.WriteString(fmt.Sprintf("// %s represents the %s event.\n", e.Name, e.Name))
	b.WriteString(fmt.Sprintf("// Topics: %v\n", e.Topics))
	b.WriteString(fmt.Sprintf("type %s struct {\n", e.Name))
	for _, f := range e.Fields {
		goType := rustTypeToGo(f.Type)
		b.WriteString(fmt.Sprintf("\t%s %s\n", snakeToPascal(f.Name), goType))
	}
	// Add metadata fields
	b.WriteString("\t// Event metadata\n")
	b.WriteString("\tLedger uint32\n")
	b.WriteString("\tTxHash string\n")
	b.WriteString("}\n\n")

	// Topic constant
	if len(e.Topics) > 0 {
		b.WriteString(fmt.Sprintf("// %sTopic is the event topic identifier.\n", e.Name))
		b.WriteString(fmt.Sprintf("const %sTopic = \"%s\"\n\n", e.Name, e.Topics[0]))
	}
}

func generateHelpers(b *strings.Builder) {
	b.WriteString(`// Helper functions for ScVal conversions

func uint64ToScVal(v uint64) xdr.ScVal {
	xdrU64 := xdr.Uint64(v)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvU64,
		U64:  &xdrU64,
	}
}

func uint32ToScVal(v uint32) xdr.ScVal {
	xdrU32 := xdr.Uint32(v)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvU32,
		U32:  &xdrU32,
	}
}

func boolToScVal(v bool) xdr.ScVal {
	return xdr.ScVal{
		Type: xdr.ScValTypeScvBool,
		B:    &v,
	}
}

func i128ToScVal(v int64) xdr.ScVal {
	var hi int64
	if v < 0 {
		hi = -1 // Sign extend for negative numbers
	}
	lo := uint64(v)
	parts := xdr.Int128Parts{
		Hi: xdr.Int64(hi),
		Lo: xdr.Uint64(lo),
	}
	return xdr.ScVal{
		Type: xdr.ScValTypeScvI128,
		I128: &parts,
	}
}

func bytesToScVal(b []byte) xdr.ScVal {
	bytes := xdr.ScBytes(b)
	return xdr.ScVal{
		Type:  xdr.ScValTypeScvBytes,
		Bytes: &bytes,
	}
}

func bytes32ToScVal(b [32]byte) xdr.ScVal {
	bytes := xdr.ScBytes(b[:])
	return xdr.ScVal{
		Type:  xdr.ScValTypeScvBytes,
		Bytes: &bytes,
	}
}

func addressToScVal(addr string) xdr.ScVal {
	scAddr := parseAddress(addr)
	return xdr.ScVal{
		Type:    xdr.ScValTypeScvAddress,
		Address: scAddr,
	}
}

func vecToScVal(items []xdr.ScVal) xdr.ScVal {
	scVec := xdr.ScVec(items)
	vecPtr := &scVec
	return xdr.ScVal{
		Type: xdr.ScValTypeScvVec,
		Vec:  &vecPtr,
	}
}

func symbolToScVal(sym string) xdr.ScVal {
	scSym := xdr.ScSymbol(sym)
	return xdr.ScVal{
		Type: xdr.ScValTypeScvSymbol,
		Sym:  &scSym,
	}
}

func buildStructScVal(fields map[string]xdr.ScVal) (xdr.ScVal, error) {
	// Soroban requires ScMap keys to be sorted lexicographically
	keys := make([]string, 0, len(fields))
	for k := range fields {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	entries := make([]xdr.ScMapEntry, 0, len(fields))
	for _, k := range keys {
		v := fields[k]
		sym := xdr.ScSymbol(k)
		entries = append(entries, xdr.ScMapEntry{
			Key: xdr.ScVal{
				Type: xdr.ScValTypeScvSymbol,
				Sym:  &sym,
			},
			Val: v,
		})
	}
	scMap := xdr.ScMap(entries)
	mapPtr := &scMap
	return xdr.ScVal{
		Type: xdr.ScValTypeScvMap,
		Map:  &mapPtr,
	}, nil
}

func parseAddress(addr string) *xdr.ScAddress {
	if len(addr) == 0 {
		return nil
	}

	if addr[0] == 'C' {
		decoded, err := strkey.Decode(strkey.VersionByteContract, addr)
		if err != nil {
			return nil
		}
		return buildContractScAddress(decoded)
	}

	if addr[0] == 'G' {
		decoded, err := strkey.Decode(strkey.VersionByteAccountID, addr)
		if err != nil {
			return nil
		}
		var pubKey xdr.Uint256
		copy(pubKey[:], decoded)
		accountID := xdr.AccountId{
			Type:    xdr.PublicKeyTypePublicKeyTypeEd25519,
			Ed25519: &pubKey,
		}
		return &xdr.ScAddress{
			Type:      xdr.ScAddressTypeScAddressTypeAccount,
			AccountId: &accountID,
		}
	}

	return nil
}

func buildContractScAddress(contractIDBytes []byte) *xdr.ScAddress {
	if len(contractIDBytes) != 32 {
		return nil
	}
	xdrBytes := make([]byte, 0, 36)
	xdrBytes = append(xdrBytes, 0, 0, 0, 1)
	xdrBytes = append(xdrBytes, contractIDBytes...)

	var addr xdr.ScAddress
	if err := addr.UnmarshalBinary(xdrBytes); err != nil {
		return nil
	}
	return &addr
}

func addressFromScVal(val xdr.ScVal) (string, error) {
	addr, ok := val.GetAddress()
	if !ok {
		return "", fmt.Errorf("not an address type: %v", val.Type)
	}

	switch addr.Type {
	case xdr.ScAddressTypeScAddressTypeAccount:
		accountID := addr.MustAccountId()
		pubKey := accountID.Ed25519
		if pubKey == nil {
			return "", fmt.Errorf("account ID has no Ed25519 key")
		}
		return strkey.Encode(strkey.VersionByteAccountID, (*pubKey)[:])
	case xdr.ScAddressTypeScAddressTypeContract:
		contractID := addr.MustContractId()
		return strkey.Encode(strkey.VersionByteContract, contractID[:])
	default:
		return "", fmt.Errorf("unsupported address type: %s", addr.Type)
	}
}

func uint64FromScVal(val xdr.ScVal) (uint64, error) {
	u64, ok := val.GetU64()
	if !ok {
		return 0, fmt.Errorf("not a u64 type: %v", val.Type)
	}
	return uint64(u64), nil
}

func bytes32FromScVal(val xdr.ScVal) ([32]byte, error) {
	bytes, ok := val.GetBytes()
	if !ok {
		return [32]byte{}, fmt.Errorf("not a bytes type: %v", val.Type)
	}
	if len(bytes) != 32 {
		return [32]byte{}, fmt.Errorf("expected 32 bytes, got %d", len(bytes))
	}
	var result [32]byte
	copy(result[:], bytes)
	return result, nil
}

func i128FromScVal(val xdr.ScVal) (int64, error) {
	i128, ok := val.GetI128()
	if !ok {
		return 0, fmt.Errorf("not an i128 type: %v", val.Type)
	}
	return int64(i128.Lo), nil
}

// mustToScVal panics if ToScVal returns an error.
func mustToScVal(val xdr.ScVal, err error) xdr.ScVal {
	if err != nil {
		panic(err)
	}
	return val
}

// addressSliceToScVal converts a slice of address strings to xdr.ScVal.
func addressSliceToScVal(items []string) xdr.ScVal {
	scVals := make([]xdr.ScVal, len(items))
	for i, item := range items {
		scVals[i] = addressToScVal(item)
	}
	return vecToScVal(scVals)
}

// structSliceToScVal converts a slice of structs with ToScVal to xdr.ScVal.
func structSliceToScVal[T interface{ ToScVal() (xdr.ScVal, error) }](items []T) xdr.ScVal {
	scVals := make([]xdr.ScVal, len(items))
	for i := range items {
		val, err := items[i].ToScVal()
		if err != nil {
			panic(err)
		}
		scVals[i] = val
	}
	return vecToScVal(scVals)
}
`)
}

// Type conversion helpers

func rustTypeToGo(rustType string) string {
	switch rustType {
	case "u64":
		return "uint64"
	case "u32":
		return "uint32"
	case "i128":
		return "int64"
	case "bool":
		return "bool"
	case "soroban_sdk::Address":
		return "string"
	case "soroban_sdk::Bytes":
		return "[]byte"
	}

	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		// Extract N
		n := strings.TrimSuffix(strings.TrimPrefix(rustType, "soroban_sdk::BytesN<"), ">")
		return fmt.Sprintf("[%s]byte", n)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::Vec<") {
		inner := extractVecInnerType(rustType)
		return "[]" + rustTypeToGo(inner)
	}

	// Assume it's a struct name
	return extractStructName(rustType)
}

func extractVecInnerType(vecType string) string {
	// soroban_sdk::Vec<InnerType>
	inner := strings.TrimSuffix(strings.TrimPrefix(vecType, "soroban_sdk::Vec<"), ">")
	return strings.TrimSpace(inner)
}

func extractStructName(rustType string) string {
	// Handle things like TokenAmount or soroban_sdk types
	if strings.Contains(rustType, "::") {
		parts := strings.Split(rustType, "::")
		return parts[len(parts)-1]
	}
	return rustType
}

func getToScValConverter(rustType, expr string) string {
	switch rustType {
	case "u64":
		return fmt.Sprintf("uint64ToScVal(%s)", expr)
	case "u32":
		return fmt.Sprintf("uint32ToScVal(%s)", expr)
	case "i128":
		return fmt.Sprintf("i128ToScVal(%s)", expr)
	case "bool":
		return fmt.Sprintf("boolToScVal(%s)", expr)
	case "soroban_sdk::Address":
		return fmt.Sprintf("addressToScVal(%s)", expr)
	case "soroban_sdk::Bytes":
		return fmt.Sprintf("bytesToScVal(%s)", expr)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::BytesN<") {
		return fmt.Sprintf("bytes32ToScVal(%s)", expr)
	}

	if strings.HasPrefix(rustType, "soroban_sdk::Vec<") {
		inner := extractVecInnerType(rustType)
		if inner == "soroban_sdk::Address" {
			return fmt.Sprintf("addressSliceToScVal(%s)", expr)
		}
		return fmt.Sprintf("structSliceToScVal(%s)", expr)
	}

	// Struct - call ToScVal
	return fmt.Sprintf("mustToScVal((%s).ToScVal())", expr)
}

func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func camelToSpaces(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && unicode.IsUpper(r) {
			result.WriteRune(' ')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
