// Code generated by stellar-bindings-generator. DO NOT EDIT.
package rmn_proxy

import (
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// RmnProxyError represents the contract error codes.
const (
	RmnProxyErrorAlreadyInitialized = 1
	RmnProxyErrorNotInitialized = 2
	RmnProxyErrorUnauthorized = 3
)

// RmnProxyErrorMessage returns a human-readable message for error codes.
var RmnProxyErrorMessage = map[int]string{
	1: "already initialized",
	2: "not initialized",
	3: "unauthorized",
}

// AuthError represents the contract error codes.
const (
	AuthErrorNotInitialized = 1
	AuthErrorUnauthorized = 2
	AuthErrorNotOwner = 3
	AuthErrorNoPendingOwner = 4
	AuthErrorCallerNotAuthorized = 5
	AuthErrorCallerAlreadyAuthorized = 6
	AuthErrorCallerNotFound = 7
	AuthErrorRoleNotGranted = 8
	AuthErrorFeatureNotEnabled = 9
	AuthErrorRoleAlreadyGranted = 10
	AuthErrorCannotRenounceRole = 11
)

// AuthErrorMessage returns a human-readable message for error codes.
var AuthErrorMessage = map[int]string{
	1: "not initialized",
	2: "unauthorized",
	3: "not owner",
	4: "no pending owner",
	5: "caller not authorized",
	6: "caller already authorized",
	7: "caller not found",
	8: "role not granted",
	9: "feature not enabled",
	10: "role already granted",
	11: "cannot renounce role",
}

// RmnSetEvent represents the RmnSetEvent event.
// Topics: [rmn_proxy_RmnSet]
type RmnSetEvent struct {
	Rmn string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RmnSetEventTopic is the event topic identifier.
const RmnSetEventTopic = "rmn_proxy_RmnSet"

// RoleGrantedEvent represents the RoleGrantedEvent event.
// Topics: [auth_RoleGranted]
type RoleGrantedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleGrantedEventTopic is the event topic identifier.
const RoleGrantedEventTopic = "auth_RoleGranted"

// RoleRevokedEvent represents the RoleRevokedEvent event.
// Topics: [auth_RoleRevoked]
type RoleRevokedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleRevokedEventTopic is the event topic identifier.
const RoleRevokedEventTopic = "auth_RoleRevoked"

// OwnershipTransferredEvent represents the OwnershipTransferredEvent event.
// Topics: [auth_OwnerTransferred]
type OwnershipTransferredEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferredEventTopic is the event topic identifier.
const OwnershipTransferredEventTopic = "auth_OwnerTransferred"

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

