// Code generated by stellar-bindings-generator. DO NOT EDIT.
package versioned_verifier_resolver

import (
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// InboundImplementationUpdate represents the InboundImplementationUpdate struct from the contract.
type InboundImplementationUpdate struct {
	Verifier Address>
	Version [4]byte
}

// ToScVal converts InboundImplementationUpdate to an xdr.ScVal for contract calls.
func (s InboundImplementationUpdate) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"verifier": scval.MustToScVal((s.Verifier).ToScVal()),
		"version": scval.Bytes32ToScVal(s.Version),
	})
}

// InboundImplementationUpdateFromScVal parses an xdr.ScVal into InboundImplementationUpdate.
func InboundImplementationUpdateFromScVal(val xdr.ScVal) (*InboundImplementationUpdate, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &InboundImplementationUpdate{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "verifier":
			v, err := Address>FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("verifier: %w", err)
			}
			result.Verifier = *v
		case "version":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("version: %w", err)
			}
			result.Version = v
		}
	}

	return result, nil
}

// InboundImplementationArgs represents the InboundImplementationArgs struct from the contract.
type InboundImplementationArgs struct {
	Verifier string
	Version [4]byte
}

// ToScVal converts InboundImplementationArgs to an xdr.ScVal for contract calls.
func (s InboundImplementationArgs) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"verifier": scval.AddressToScVal(s.Verifier),
		"version": scval.Bytes32ToScVal(s.Version),
	})
}

// InboundImplementationArgsFromScVal parses an xdr.ScVal into InboundImplementationArgs.
func InboundImplementationArgsFromScVal(val xdr.ScVal) (*InboundImplementationArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &InboundImplementationArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "verifier":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("verifier: %w", err)
			}
			result.Verifier = v
		case "version":
			v, err := scval.Bytes32FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("version: %w", err)
			}
			result.Version = v
		}
	}

	return result, nil
}

// OutboundImplementationUpdate represents the OutboundImplementationUpdate struct from the contract.
type OutboundImplementationUpdate struct {
	DestChainSelector uint64
	Verifier Address>
}

// ToScVal converts OutboundImplementationUpdate to an xdr.ScVal for contract calls.
func (s OutboundImplementationUpdate) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"verifier": scval.MustToScVal((s.Verifier).ToScVal()),
	})
}

// OutboundImplementationUpdateFromScVal parses an xdr.ScVal into OutboundImplementationUpdate.
func OutboundImplementationUpdateFromScVal(val xdr.ScVal) (*OutboundImplementationUpdate, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &OutboundImplementationUpdate{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "verifier":
			v, err := Address>FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("verifier: %w", err)
			}
			result.Verifier = *v
		}
	}

	return result, nil
}

// OutboundImplementationArgs represents the OutboundImplementationArgs struct from the contract.
type OutboundImplementationArgs struct {
	DestChainSelector uint64
	Verifier string
}

// ToScVal converts OutboundImplementationArgs to an xdr.ScVal for contract calls.
func (s OutboundImplementationArgs) ToScVal() (xdr.ScVal, error) {
	return scval.BuildStructScVal(map[string]xdr.ScVal{
		"dest_chain_selector": scval.Uint64ToScVal(s.DestChainSelector),
		"verifier": scval.AddressToScVal(s.Verifier),
	})
}

// OutboundImplementationArgsFromScVal parses an xdr.ScVal into OutboundImplementationArgs.
func OutboundImplementationArgsFromScVal(val xdr.ScVal) (*OutboundImplementationArgs, error) {
	scMap, ok := val.GetMap()
	if !ok || scMap == nil {
		return nil, fmt.Errorf("not a map type")
	}

	result := &OutboundImplementationArgs{}
	for _, entry := range *scMap {
		key, ok := entry.Key.GetSym()
		if !ok {
			continue
		}

		switch string(key) {
		case "dest_chain_selector":
			v, err := scval.Uint64FromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("dest_chain_selector: %w", err)
			}
			result.DestChainSelector = v
		case "verifier":
			v, err := scval.AddressFromScVal(entry.Val)
			if err != nil {
				return nil, fmt.Errorf("verifier: %w", err)
			}
			result.Verifier = v
		}
	}

	return result, nil
}

// VerifierResolverError represents the contract error codes.
const (
	VerifierResolverErrorAlreadyInitialized = 1
	VerifierResolverErrorNotInitialized = 2
	VerifierResolverErrorUnauthorized = 3
	VerifierResolverErrorInvalidVerifierResultsLength = 4
	VerifierResolverErrorInboundImplementationNotFound = 5
	VerifierResolverErrorOutboundImplementationNotFound = 6
	VerifierResolverErrorInvalidAddress = 7
	VerifierResolverErrorInvalidChainSelector = 8
	VerifierResolverErrorInvalidVersion = 9
)

// VerifierResolverErrorMessage returns a human-readable message for error codes.
var VerifierResolverErrorMessage = map[int]string{
	1: "already initialized",
	2: "not initialized",
	3: "unauthorized",
	4: "invalid verifier results length",
	5: "inbound implementation not found",
	6: "outbound implementation not found",
	7: "invalid address",
	8: "invalid chain selector",
	9: "invalid version",
}

// AuthError represents the contract error codes.
const (
	AuthErrorNotInitialized = 1
	AuthErrorUnauthorized = 2
	AuthErrorNotOwner = 3
	AuthErrorNoPendingOwner = 4
	AuthErrorCallerNotAuthorized = 5
	AuthErrorCallerAlreadyAuthorized = 6
	AuthErrorCallerNotFound = 7
	AuthErrorRoleNotGranted = 8
	AuthErrorFeatureNotEnabled = 9
	AuthErrorRoleAlreadyGranted = 10
	AuthErrorCannotRenounceRole = 11
)

// AuthErrorMessage returns a human-readable message for error codes.
var AuthErrorMessage = map[int]string{
	1: "not initialized",
	2: "unauthorized",
	3: "not owner",
	4: "no pending owner",
	5: "caller not authorized",
	6: "caller already authorized",
	7: "caller not found",
	8: "role not granted",
	9: "feature not enabled",
	10: "role already granted",
	11: "cannot renounce role",
}

// InboundImplSetEvent represents the InboundImplSetEvent event.
// Topics: [vvr_InboundImplSet]
type InboundImplSetEvent struct {
	Version [4]byte
	Verifier string
	// Event metadata
	Ledger uint32
	TxHash string
}

// InboundImplSetEventTopic is the event topic identifier.
const InboundImplSetEventTopic = "vvr_InboundImplSet"

// InboundImplRemovedEvent represents the InboundImplRemovedEvent event.
// Topics: [vvr_InboundImplRemoved]
type InboundImplRemovedEvent struct {
	Version [4]byte
	// Event metadata
	Ledger uint32
	TxHash string
}

// InboundImplRemovedEventTopic is the event topic identifier.
const InboundImplRemovedEventTopic = "vvr_InboundImplRemoved"

// OutboundImplSetEvent represents the OutboundImplSetEvent event.
// Topics: [vvr_OutboundImplSet]
type OutboundImplSetEvent struct {
	DestChainSelector uint64
	Verifier string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OutboundImplSetEventTopic is the event topic identifier.
const OutboundImplSetEventTopic = "vvr_OutboundImplSet"

// OutboundImplRemovedEvent represents the OutboundImplRemovedEvent event.
// Topics: [vvr_OutboundImplRemoved]
type OutboundImplRemovedEvent struct {
	DestChainSelector uint64
	// Event metadata
	Ledger uint32
	TxHash string
}

// OutboundImplRemovedEventTopic is the event topic identifier.
const OutboundImplRemovedEventTopic = "vvr_OutboundImplRemoved"

// FeeAggregatorSetEvent represents the FeeAggregatorSetEvent event.
// Topics: [vvr_FeeAggregatorSet]
type FeeAggregatorSetEvent struct {
	FeeAggregator string
	// Event metadata
	Ledger uint32
	TxHash string
}

// FeeAggregatorSetEventTopic is the event topic identifier.
const FeeAggregatorSetEventTopic = "vvr_FeeAggregatorSet"

// OwnershipTransferredEvent represents the OwnershipTransferredEvent event.
// Topics: [vvr_OwnerTransferred]
type OwnershipTransferredEvent struct {
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferredEventTopic is the event topic identifier.
const OwnershipTransferredEventTopic = "vvr_OwnerTransferred"

// OwnershipTransferStartedEvent represents the OwnershipTransferStartedEvent event.
// Topics: [auth_OwnerTransferStart]
type OwnershipTransferStartedEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferStartedEventTopic is the event topic identifier.
const OwnershipTransferStartedEventTopic = "auth_OwnerTransferStart"

// OwnershipTransferredEvent represents the OwnershipTransferredEvent event.
// Topics: [auth_OwnerTransferred]
type OwnershipTransferredEvent struct {
	PreviousOwner string
	NewOwner string
	// Event metadata
	Ledger uint32
	TxHash string
}

// OwnershipTransferredEventTopic is the event topic identifier.
const OwnershipTransferredEventTopic = "auth_OwnerTransferred"

// AuthorizedCallerAddedEvent represents the AuthorizedCallerAddedEvent event.
// Topics: [auth_CallerAdded]
type AuthorizedCallerAddedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerAddedEventTopic is the event topic identifier.
const AuthorizedCallerAddedEventTopic = "auth_CallerAdded"

// AuthorizedCallerRemovedEvent represents the AuthorizedCallerRemovedEvent event.
// Topics: [auth_CallerRemoved]
type AuthorizedCallerRemovedEvent struct {
	Caller string
	// Event metadata
	Ledger uint32
	TxHash string
}

// AuthorizedCallerRemovedEventTopic is the event topic identifier.
const AuthorizedCallerRemovedEventTopic = "auth_CallerRemoved"

// RoleGrantedEvent represents the RoleGrantedEvent event.
// Topics: [auth_RoleGranted]
type RoleGrantedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleGrantedEventTopic is the event topic identifier.
const RoleGrantedEventTopic = "auth_RoleGranted"

// RoleRevokedEvent represents the RoleRevokedEvent event.
// Topics: [auth_RoleRevoked]
type RoleRevokedEvent struct {
	Role Symbol
	Account string
	Sender string
	// Event metadata
	Ledger uint32
	TxHash string
}

// RoleRevokedEventTopic is the event topic identifier.
const RoleRevokedEventTopic = "auth_RoleRevoked"

