// Code generated by stellar-bindings-generator. DO NOT EDIT.
package token_pool

import (
	"context"
	"fmt"

	"github.com/smartcontractkit/chainlink-stellar/bindings"
	"github.com/smartcontractkit/chainlink-stellar/bindings/scval"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// TokenPoolClient provides methods to interact with the TokenPool contract.
type TokenPoolClient struct {
	invoker    bindings.Invoker
	contractID string
}

// NewTokenPoolClient creates a new TokenPoolClient.
func NewTokenPoolClient(invoker bindings.Invoker, contractID string) *TokenPoolClient {
	return &TokenPoolClient{
		invoker:    invoker,
		contractID: contractID,
	}
}

// ContractID returns the contract ID.
func (c *TokenPoolClient) ContractID() string {
	return c.contractID
}

// Initialize calls the initialize function on the contract.
func (c *TokenPoolClient) Initialize(ctx context.Context, owner string, token string, tokenDecimals uint32) error {
	args := []xdr.ScVal{
		scval.AddressToScVal(owner),
		scval.AddressToScVal(token),
		scval.Uint32ToScVal(tokenDecimals),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "initialize", args)
	if err != nil {
		return fmt.Errorf("failed to call initialize: %w", err)
	}

	_ = result // void return
	return nil
}

// LockOrBurn calls the lock_or_burn function on the contract.
func (c *TokenPoolClient) LockOrBurn(ctx context.Context, input LockOrBurnIn) (*LockOrBurnOut, error) {
	args := []xdr.ScVal{
		scval.MustToScVal(input.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "lock_or_burn", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call lock_or_burn: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from lock_or_burn")
	}

	return LockOrBurnOutFromScVal(*result)
}

// ReleaseOrMint calls the release_or_mint function on the contract.
func (c *TokenPoolClient) ReleaseOrMint(ctx context.Context, input ReleaseOrMintIn) (*ReleaseOrMintOut, error) {
	args := []xdr.ScVal{
		scval.MustToScVal(input.ToScVal()),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "release_or_mint", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call release_or_mint: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from release_or_mint")
	}

	return ReleaseOrMintOutFromScVal(*result)
}

// IsSupportedToken calls the is_supported_token function on the contract.
func (c *TokenPoolClient) IsSupportedToken(ctx context.Context, token string) (bool, error) {
	args := []xdr.ScVal{
		scval.AddressToScVal(token),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_token", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_token: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_token")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// IsSupportedChain calls the is_supported_chain function on the contract.
func (c *TokenPoolClient) IsSupportedChain(ctx context.Context, remoteChainSelector uint64) (bool, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "is_supported_chain", args)
	if err != nil {
		return false, fmt.Errorf("failed to call is_supported_chain: %w", err)
	}

	if result == nil {
		return false, fmt.Errorf("no return value from is_supported_chain")
	}

	v, ok := result.GetB()
	if !ok {
		return false, fmt.Errorf("expected bool return type")
	}
	return v, nil
}

// GetToken calls the get_token function on the contract.
func (c *TokenPoolClient) GetToken(ctx context.Context) (string, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token", args)
	if err != nil {
		return "", fmt.Errorf("failed to call get_token: %w", err)
	}

	if result == nil {
		return "", fmt.Errorf("no return value from get_token")
	}

	v, err := scval.AddressFromScVal(*result)
	if err != nil {
		return "", err
	}
	return v, nil
}

// GetTokenDecimals calls the get_token_decimals function on the contract.
func (c *TokenPoolClient) GetTokenDecimals(ctx context.Context) (uint32, error) {
	args := []xdr.ScVal{}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_token_decimals", args)
	if err != nil {
		return 0, fmt.Errorf("failed to call get_token_decimals: %w", err)
	}

	if result == nil {
		return 0, fmt.Errorf("no return value from get_token_decimals")
	}

	if result.Type != xdr.ScValTypeScvU32 || result.U32 == nil {
		return 0, fmt.Errorf("expected u32 return type")
	}
	return uint32(*result.U32), nil
}

// GetRemotePool calls the get_remote_pool function on the contract.
func (c *TokenPoolClient) GetRemotePool(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_pool", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_pool: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_pool")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// GetRemoteToken calls the get_remote_token function on the contract.
func (c *TokenPoolClient) GetRemoteToken(ctx context.Context, remoteChainSelector uint64) ([]byte, error) {
	args := []xdr.ScVal{
		scval.Uint64ToScVal(remoteChainSelector),
	}

	result, err := c.invoker.SimulateContract(ctx, c.contractID, "get_remote_token", args)
	if err != nil {
		return nil, fmt.Errorf("failed to call get_remote_token: %w", err)
	}

	if result == nil {
		return nil, fmt.Errorf("no return value from get_remote_token")
	}

	v, ok := result.GetBytes()
	if !ok {
		return nil, fmt.Errorf("expected bytes return type")
	}
	return []byte(v), nil
}

// ApplyChainUpdates calls the apply_chain_updates function on the contract.
func (c *TokenPoolClient) ApplyChainUpdates(ctx context.Context, adds []ChainUpdate, removes []uint64) error {
	args := []xdr.ScVal{
		scval.StructSliceToScVal(adds),
		scval.Uint64SliceToScVal(removes),
	}

	result, err := c.invoker.InvokeContract(ctx, c.contractID, "apply_chain_updates", args)
	if err != nil {
		return fmt.Errorf("failed to call apply_chain_updates: %w", err)
	}

	_ = result // void return
	return nil
}
